// What people say when you talk to them (E): the mess workers, stall owners, shopkeepers, sweepers, gardeners, lab staff,
// librarians and the medical staff.

export const mess = [
  'Dinner is from a quarter to eight. Do not be late, the rice finishes first!',
  'Wash your plate there, beta, and put it on the rack. The rack, not the table.',
  'Take only what you can eat. Waste is not a joke, someone cooked it since the morning.',
  'The dal is fresh today. The roti is hot. The sabji, well, it is sabji.',
  'Guest coupon? Fifty rupees for breakfast, seventy-five for lunch and for dinner. Sunday dinner is ninety.',
  'Your own hostel eats free with the mess card. Guests from other hostels pay the coupon price.',
  'Breakfast is from half past seven to half past nine. After that, the kitchen is closed and the tea is cold.',
  'Lunch from a quarter past twelve to two. After two, ask your friend to save you something.',
  'Dinner from a quarter to eight to a quarter to ten. The last ten minutes are the busiest.',
  'There is a menu board near the door. Read it before you enter, so you do not stand and think in the queue.',
  'Sunday special thali has everything: paneer, chicken, two sweets, ice cream. Come early.',
  'Take a plate from the pile, there. Then the queue. Then the counter. Then eat. Then wash. It is simple!',
  'The mess committee decides the menu. If you do not like it, join the committee, do not shout at me.',
  'Rice, dal, sabji, roti, curd, salad, papad. That is the usual lunch, and some days a sweet too.',
  'Friday has biryani in many hostels. People come from all the others, and they pretend it is a coincidence.',
  'Tuesday is the day for the egg curry. The vegetarians have the dum aloo. Everyone is happy, or nearly.',
  'Aloo paratha for breakfast on Monday. Curd and pickle. Eat slowly and live longer.',
  'Poha on Tuesday, idli on Wednesday, puri on Thursday. Dosa on Friday, and chole kulche on the weekend.',
  'The kitchen starts at five. By seven the first chai is ready, and by half past seven the line starts.',
  'The cook has been here for fifteen years. He knows who likes less salt and who likes more.',
  'We cook for hundreds of students three times a day. A pinch of patience is the main ingredient.',
  'If there is a hair in the food, tell me, not the whole hostel. I will change the plate.',
  'The mess is cleaned every night. The floor is washed after dinner, so please do not drop the dal.',
  'Water cooler is at the back. Fill your bottle and carry it to the room.',
  'Take a glass of buttermilk when it is hot. The hostel summer is long.',
  'Do not take food to the room. The ants take over the corridor, and then the warden shouts at me.',
  'In Bihu week we make pitha and laru. Everyone becomes an Assamese for a day.',
  'The cook from Assam makes the best fish curry. Tenga, with lemon. Try it on Thursday.',
  'On Diwali we cook a big feast. Even the guard sits down to eat with us.',
  'Be kind to the servers. They stand for hours and smile for all of you.',
  'You are new? The queue is two lanes: roti and rice. You can switch at the dal.',
  'The curd comes at the end of the line. Do not take two bowls, others are waiting.',
  'Papad is crisp today. The monsoon makes it soft, so we fry it fresh.',
  'The kheer was made with milk from the dairy. Slowly, for two hours.',
  'Take a plate, leave a plate. It is the rule of the mess.',
  'If you come late, the dal may be thin. That is the last of the pot, not a joke.',
  'Evening snacks are not served here. The canteen upstairs is for that, after six.',
  'The canteen on the second floor opens at six in the evening. It stays open until two at night.',
  'The first year students take three plates the first week, and one plate by the end of the semester.',
  'Mess fees are decided by the committee and the warden. We only cook what the budget allows.',
  'I like the early morning. The campus is quiet, and the kitchen is warm.',
  'I wake up at four. The milk van comes at half past, and nobody else is awake to hear it.',
  'The vegetables come from the market in the morning. The best ones go to the mess first.',
  'On Sundays we make a bigger lunch, and the students sleep through it.',
  'The cooking oil is changed often. Do not believe the rumours.',
  'We keep a record of how much is wasted. The numbers go on the notice board.',
  'The best compliment is an empty plate. The second best is a thank you.',
  'Some of you eat with your eyes closed, thinking about the exam. We understand.',
  'Be careful with the hot dal. The steel plate keeps the heat longer than you think.',
  'Your friend from the other hostel needs a coupon. Show the QR at the counter and pay by UPI.',
  'Cash is also fine. The counter has change, unless it is the first of the month.',
  'The counter closes five minutes before the meal ends. Do not blame the clerk.',
  'Take your time with the rice. It is the one thing that is always enough.',
  'We have a small garden behind the mess. The curry leaves come from there.',
  'I came here from a village in Barak Valley. The kitchen is my home now.',
  'My children are in the school here. They say the mess food is the best, but they have not eaten anywhere else.',
  'When it rains the dal tastes better. I do not know why.',
  'Do not run in the mess. The floor is wet at all times, from the cleaning and from the dal.',
  'Make a friend in the mess. Some of the best friendships here began with a shared papad.',
  'The warden visits at random. The kitchen is always ready.',
  'If you are sick, tell us. We will make a plain khichdi for you.',
  'The chicken day is the day with the longest queue. Think about it.',
  'The cook says the secret is the masala. The secret is also the salt.',
  'In winter we make hot soup for the exam week. It helps, a little.',
  'Wash your hands before eating, and after. The tap is at the back.',
  'The hot water is on from six to eight. After that it is the cold tap.',
  'The mess hall is also where the hostel meets. Elections, quizzes and cricket on the TV.',
  'We feed hundreds, and every one thinks the portion is for only them.',
  'The roti machine broke last week. The rotis you eat today were rolled by hand.',
  'There are two kinds of students: the ones who say thank you to the cook, and the ones who say it later.',
  'We close the kitchen at ten. After that the stove is off, and the cat takes the leftovers.',
  'The cat is called Mili. She comes at nine every night. Do not feed her the sweets.',
  'If you see a cockroach, tell us, we will spray. If you see a rat, scream loudly.',
  'We clean the tanks every month. The water is safe, and the filter is changed on time.',
  'I started as a helper and now I am the head cook. If you work hard, things change.',
  'If you want an extra egg, ask nicely. Maybe I will say yes.',
  'The Sunday ice cream is the reason the hostel mess is full on Sundays.',
  'On the day of the cricket final the mess serves a special lunch. The winning hostel gets extra sweets.',
  'We make a lot of rice. A lot. If a student asks for more, we are happy. It means they liked it.',
  'The spoon is for the rice, the ladle for the dal, and the hand for the roti. Do not mix them up.',
  'The tables are cleaned after every batch. Please do not leave your plate behind.',
  'My day starts before yours and ends after yours. Thanks for coming, anyway.',
  'There is a suggestion book at the counter. Write your comments. We read them in the evening.',
  'I do not take tips. A smile is enough.',
  'The mess belongs to everyone. Treat it with the respect of a home.',
  'On festival days the menu changes. Look at the board at the door.',
  'Do not take the steel plates out. We count them every night, and one is missing each week.',
  'When you graduate, you will remember the mess more than the lecture. It is the truth.',
];

export const vendor = [
  'Chai lenge? Fresh kulhad, ten rupees.',
  'Hot noodles coming up, bhaiya. Two minutes.',
  'Egg roll special today! With extra onions.',
  'Pay by UPI or cash, anything works.',
  'Tea with ginger, tea with lemon, tea with plain milk. What will it be?',
  'The samosa is hot. Only two left. Take one, or it is gone.',
  'Bun omelette for breakfast, bhaiya. Best way to start a Monday.',
  'Cold coffee, thirty rupees. Chocolate, forty. Both are cold.',
  'My stall is here since before most of you were born. The tea is the same, and so is the price. Almost.',
  'If you stand here for a minute, the smell of tea will do the rest.',
  'This is the place where the best exam plans are made.',
  'In winter the tea sells twice as fast. In summer I sell the lemon soda.',
  'In the monsoon I cover the stall with a plastic sheet and pretend it is a house.',
  'The kulhad is made of clay. It is better for the tea and for the planet.',
  'Pani puri is all about the water. Mine has a secret ingredient, and it is mint.',
  'Momos with the red chutney, and the other with the green. Take both, and the day is better.',
  'Fresh juice! Orange, pineapple, sugarcane. Sugarcane is the best, trust me.',
  'Please keep the plates on the table. The stray dogs have their own plates, near the tree.',
  'The students come in the evening in groups. The groups get bigger at exam time.',
  'The first-year students ask for the menu. The seniors ask for the usual.',
  'Remember to take the change. I always forget to give it back and then I feel bad.',
  'I wake up at five to boil the milk. The tea needs patience, and the milk needs a good fire.',
  'Everyone has a favourite order. Yours is the chai with less sugar, isn\'t it?',
  'You look tired. A hot chai and a biscuit will fix a lot.',
  'The noodles come with an egg for ten more. The egg is a good deal.',
  'The paneer roll is the most popular. The egg roll is the cheapest. The chicken roll is the best.',
  'Rolls, rolls, rolls! Fresh and hot, wrapped in paper.',
  'The stall by the lake has the best view. Mine has the best tea.',
  'The Lake View Tea Stall is the old Tapri, near the lake. Chai, samosa and bun omelette, all day.',
  'The Khokha side market has more stalls. Here is the quieter side.',
  'I have a stall at the market and a stall at the lake. The market one is for the lunch crowd.',
  'During Alcheringa my stall runs out by nine. The visitors are hungry and they do not argue about the price.',
  'During Techniche I sell more cold drinks than tea. The engineers are hot, I think.',
  'The students are good people. They talk to me about everything, except the bill.',
  'If you do not have change, pay later. I trust you. The notebook is here, and so is the number.',
  'I never forget a face, or a debt, but I forgive both.',
  'Take a small sip first. The kulhad is hot, the tea is hotter.',
  'Take your time, sit down. The bench is not comfortable, but the chai is.',
  'Plastic is not allowed on campus. I use paper cups and clay. Please do not throw them on the grass.',
  'Please throw the cup in the bin. Green is for wet, blue is for dry. The clay is neither.',
  'The gas cylinder lasts four days. When it ends, the whole stall sighs.',
  'The best time for tea is four in the afternoon. The second best is any other time.',
  'You want it sweeter? I put two spoons, not three. Three is a sin.',
  'The cold drinks are in the box with ice. Take the one on top, it is the coldest.',
  'The biscuits are fresh. The packet says so, and I believe it.',
  'A dog sleeps near my stall. His name is Raja. He gets the leftover biscuits.',
  'Rain is bad for business and good for the tea. It evens out.',
  'Business was slow during the vacation. When the students return, the stall wakes up with them.',
  'I have studied up to the tenth class. My son is in the school here, he wants to be an engineer.',
  'I came here from Nalbari to sell tea. Now I know half the campus by name.',
  'My day: tea at six, noodles at nine, rolls at twelve, tea again at four, and dinner at the stall at ten.',
  'The professors also come. They sit in the back and pay in coins.',
  'The Director once took a cup of tea from my stall. It was a good day.',
  'If you want something that is not on the list, tell me. I try.',
  'Egg, onion, chilli, bread. A bread omelette is a simple joy.',
  'The omelette is two eggs. For the big hunger, ask for three.',
  'The fried rice is the best on the campus. Not the best in the world. Close enough.',
  'Pizza? That is at the market. I only make what I can make well.',
  'The Cafe Coffee Day has the coffee. I have the chai. Nobody argues.',
  'Fruits are fresh. Banana, apple, papaya. Take a plate for the room.',
  'There is a fruit cart near the hostel gate. The vendor is very kind and very fast.',
  'The stall closes after the last customer. Some nights that is at one.',
  'In the winter I add a pinch of tulsi to the tea. It helps the cough.',
  'Kids come after school for the candy. I sell the candy for one rupee, and it is the best business in the world.',
  'I like it when students laugh. It is the best sound at the stall.',
  'If you are new, welcome. The first cup is half-price. Do not tell the others.',
  'The mug for the chai is clean, I promise. I wash it, and then I wash it again.',
  'The water for the tea is from the filter. The students have a taste for it.',
  'Give me one minute and I will make the best noodles of your day.',
  'Do you want it spicy? Medium? Mild? The spice is a personal matter.',
  'The jalebi is for the weekend only. Come early.',
  'I hope you had a good lecture. If not, the tea is on the house. Almost.',
  'For exam week I stay open until two. The tea machine does not sleep.',
  'The stall here is the stage, and the customers are the show.',
  'I like the lake in the evening. The sun goes down and the stall lights come on.',
  'Take a photograph of the stall if you want. Tell me, so that I smile.',
  'The best business advice I got: serve hot, serve fast, and smile.',
  'On Sundays I go home to my village. My brother runs the stall, and the tea is worse.',
  'The student who writes the best poem about my tea gets a free cup. No one has won yet.',
  'Buy a cup and keep a friend. That is how it works.',
];

export const shop = [
  'What do you need? Notebooks, soap, biscuits, we have everything.',
  'Recharge? Come to the mobile shop next door.',
  'A water bottle is twenty rupees, a pen is five, and a notebook is forty.',
  'We have an umbrella. The campus rain does not wait.',
  'Toothpaste, soap, shampoo. The first-year students always forget one of them.',
  'The biscuits are fresh. The batch came this morning.',
  'The cakes are baked today. One for the birthday boy, one for you.',
  'If you need a medicine, the pharmacy is at the hospital. We only sell the common ones.',
  'The shop opens at half past eight and closes at half past nine. The owner is my brother.',
  'Fresh bread, butter and eggs. The omelette men take them all before nine.',
  'Snacks for the hostel night: chips, namkeen, instant noodles. We know what exam week means.',
  'A calculator? Yes. A cheap one, a good one and a scientific one. The scientific one is not cheap.',
  'We sell charging cables, earphones and the batteries nobody remembers to buy.',
  'You can pay by UPI, card or cash. I accept all, and I forget none.',
  'The shop is small, but the stock is big. If it is not on the shelf, it is in the back.',
  'Pens, pencils, notebooks, graph paper. The stationery section is that corner.',
  'We have the lab coat. It is white, and it will not stay that way.',
  'Do you need photocopies? The machine is at the back. Two rupees a page, one rupee for a hundred.',
  'The Market Complex has everything: a bank, a barber, a tailor, a few eateries and us.',
  'If you need a tailor for the convocation suit, go to the first floor. He is good, and quick.',
  'The barber closes on Tuesdays. The shop, on the other hand, is open all week.',
  'There is a stationery shop at every hostel too. But we have the biggest range.',
  'I keep a list of what the students ask for. Next month I will have it in stock.',
  'The first of the month is the busiest. The parents have sent the money, and the students have remembered.',
  'The end of the month is quiet. The students are saving money for the dinner.',
  'I give credit to the regulars. The notebook is full of names, and the notebook never lies.',
  'We try to stock local things: Assam tea, gamosa, and the best jaggery.',
  'The Assam tea is good. The gamosa is a gift for the family. The jaggery is for the sweet tooth.',
  'Wet wipes, sanitiser, tissues. The basic things, in all sizes.',
  'The fruits are from the cart outside. The fruit man is very fast, and the oranges are sweet.',
  'The bag is cheap and it lasts a year. After that, it is a story.',
  'Cycle lock? Over there. Every student buys one. Then every student loses the key.',
  'The cycle shop is further down the road. I only sell the small things.',
  'The first-year students buy everything. The final-year students buy nothing, except tea.',
  'You can leave your parcel here. I will keep it until the evening.',
  'Delivery riders come here to ask for directions. I know all the hostel names now.',
  'The monsoon is the best time for umbrellas and the worst for the roof.',
  'I have worked here for twelve years. My first customers are now professors.',
  'Do come back. A shop is only as good as its customers.',
  'If you find a better price, tell me. I try to match it. Within reason.',
  'The shop plays the radio all day. Old songs, mostly, and a little bit of news.',
  'The power is off? I have a candle. And the lights are the last thing I switch off.',
  'We sell light bulbs, plugs and the small fixes. The warden sends the students here.',
  'A broken cup, a broken charger, a broken heart: only the first two can be fixed here.',
  'I had a student who paid me back after ten years. With interest, and a smile.',
  'The special offer today: two notebooks for the price of one and a half.',
  'We sell greeting cards for the birthday, the festival and the apology.',
  'Whiteboard markers, sketch pens, chart paper. The project season brings the crowd.',
  'We are open on Sundays too. The students need things on Sundays more than on other days.',
  'Sorry, no change. Do you have a small note? Or shall I owe you?',
  'The sugar, the tea leaves and the milk powder go out first. The hostel kettles never rest.',
  'The Lake View Tea Stall is near the lake. I only sell what is in the packet.',
  'A good shop is clean and honest. A great shop knows what you will ask for before you ask.',
  'The thing about shops: a smile is free, and it sells more than the discount.',
  'Please check the date on the packet. I check too, but your eyes are young.',
  'The students pay on the first of the month. The rest of the month they pay in promises.',
  'My shelf has a thousand things. The one thing it does not have is the thing you need.',
  'I will order it for you. It comes on the third day.',
  'The mobile shop next door can fix the screen. I can fix the cover.',
  'I sell the cheapest umbrella and the cheapest earphones. They are not related.',
  'For the festival I stock lights and decorations. The hostels buy them by the dozen.',
  'On Holi I sell colour. On Diwali I sell lamps. On the other days I sell notebooks.',
  'There is a wall of posters. They are for sale, and for the walls of the rooms.',
  'The poster with the sunset is the most popular. It is the one at the lake.',
  'Please bring back the bag. I charge a rupee, and I refund it.',
  'I do not sell cigarettes. This is a campus, and I have a conscience.',
  'The shop has a first-aid corner: a plaster, a bandage and an antiseptic. For small cuts.',
  'The people who work here are from the village near the campus. We are proud of the institute.',
  'It is a good job. The students are polite, and the days go quickly.',
  'I like the afternoon, when the market is quiet and the fan is slow.',
  'The foreign students like the tea and the biscuits. They ask me for the names in Assamese.',
  'The first day of the semester is like a festival. Everyone buys everything.',
  'I cannot give a discount on the notebooks. The paper is expensive.',
  'The best thing on the shelf is the one you did not know you needed.',
  'You can leave your list. I will pack it for the evening.',
  'If you buy a bag, I will give you a pen. If you buy two bags, ask my brother.',
];

export const sweeper = [
  'Namaskar! Please use the dustbins, green for wet, blue for dry.',
  'The leaves never stop falling here.',
  'I start at six, before the students wake up. By nine the roads are clean and by ten they are not.',
  'Mind the broom, please. I am sweeping, and the wind is not helping.',
  'The wet leaves are the hardest. They stick to the road after the rain.',
  'The monsoon is the best time for the trees and the worst for me.',
  'Please walk on the other side. The dust will go in your eyes.',
  'The bins at the hostels are emptied in the morning. The bins at the stalls, in the evening.',
  'Green for wet waste, blue for dry. It is not difficult, and it makes my job easier.',
  'Do not throw the chai cup on the road. I will pick it up, but I will remember your face.',
  'I have a section: from the hostel gate to the circle. Every leaf in it is mine.',
  'The lake side is the cleanest, because the ducks eat everything. Not really, but it looks clean.',
  'I clean the road near the stalls last. The students do not wait for the broom.',
  'In winter the leaves are dry and light. They blow away before I finish.',
  'Sometimes I find a pen or a key. I give it to the guard, and the owner comes back.',
  'My day ends at two. Then I go home and sleep for an hour, and the evening is mine.',
  'I have been working on the campus for twenty years. The roads are new, the leaves are old.',
  'The new two-lane roads are wide. The green cycle strips are easy to sweep. The flower beds, not so much.',
  'The gardeners cut the grass, and I clean up after. We are a team.',
  'The sand from the construction site blows onto the road. I sweep it twice a day.',
  'The students are good. A few throw the bottles on the grass, but most use the bin.',
  'When I started, there were no bins at the gate. Now there are two, and they are always full.',
  'The Rhino Circle gets a lot of leaves. The big trees there are very generous.',
  'On the day of the festival the campus is full of paper and plastic. We work until midnight.',
  'Alcheringa leaves a lot of waste. The volunteers help, and we finish by the next morning.',
  'The campus is big, and we are few. Please help us keep it clean.',
  'I like the early morning. The roads are quiet, the air is cool, and the birds are loud.',
  'I wave to the guards every morning. They wave back with a tea cup.',
  'The best part of the job is the walk. The worst part is the dust.',
  'The children of the staff play near the road. I sweep around them.',
  'I take the cycle to my section. It is a long way, and the cycle is old.',
  'Do not worry about the dust. It will settle by the time you come back.',
  'If you see a banana peel, step over it. Or pick it up. Please.',
  'I have a plastic bag for the plastic and a basket for the leaves. The wet leaves go to the compost.',
  'The compost pit is behind the hostel. The gardeners use it for the flower beds.',
  'The hostel corridors are cleaned by another team. I only do the roads.',
  'I do not mind the work. I mind the people who do not say good morning.',
  'The sweepers have a meeting every month. We discuss the routes, and the new brooms.',
  'The broom is made of dried grass. The best ones come from the village near the river.',
  'I wear gloves and a mask in the dusty season. The institute gives us both.',
  'The guard gives me a cup of tea when it is cold. I give him a leaf when it is warm. We are even.',
  'The jackals leave the hill road alone, and I leave their tracks alone.',
  'The dogs follow me around. They think I am going to feed them.',
  'It is a quiet job, but it is an important one. A clean road is a happy road.',
  'I like it when a student says thank you. It happens once a month, but it is a good day.',
  'The ducks near the lake are noisy at six. I think they are discussing the weather.',
  'My son wants to study at the institute. I tell him to work hard.',
  'The spring is the best season. The new leaves are green and the old leaves are on the ground.',
  'The road to the library is always full of papers. The students throw their notes on the way.',
  'It is a long road to the gate, but I know every crack on it.',
  'The long road to the View Point trail is not mine. The forest keeps itself clean.',
  'The leaves from the amaltas are yellow and beautiful, and a nightmare to sweep.',
  'The rain makes the road shine. It is the only time my work looks perfect.',
  'The students ride fast on the downhill. I move my broom and they say sorry. It is fine.',
  'If you drop something, I will not pick it up for you, but I will watch where it goes.',
  'I like the festival days when the roads are decorated. I clean them after, not before.',
  'The campus has a small recycling shed. I take the bottles there, and they are collected on Fridays.',
  'I know the trees here by their leaves. The mango, the neem, the gulmohar.',
  'It is my job to keep the roads clean, and yours to keep them that way.',
  'The Khokha side has more waste. The market is busy, and the bins are small.',
  'I hope you have a good day. The road ahead is clean.',
  'The sun is up, the road is clean, and my tea is cold. A normal morning.',
  'We start at six, even on Sundays. The leaves do not take a holiday.',
  'There is a fine for littering, but I have never seen it used. A word is enough.',
  'The best thing about this job is the people I meet, and the worst is the dust in my tea.',
  'The rain washes the road, and the road washes my mood.',
  'Be careful on the wet road. The leaves are slippery, and so are the excuses.',
  'The new bins have a lid. The dogs cannot open them, and I am grateful.',
  'The monkeys near the hill pull the bags out. I put them back, and they pull them out again.',
  'The path by the lake is my favourite. I stop for a minute and look at the water.',
  'I wish you a good day, and a clean one.',
  'The institute gave us new uniforms last year. We look like we run the place. A bit.',
  'If you see me, wave. I do not get many waves.',
  'The best view of the campus is at six in the morning, from the top of the road.',
  'A good broom lasts a month. A good friend lasts a lifetime. I have both.',
  'It takes a lot of leaves to make a mountain. I have a small mountain behind the hostel.',
];

export const gardener = [
  'The gulmohar will bloom next month. Beautiful, you will see.',
  'Please do not walk on the new grass. It takes a month to grow and a minute to ruin.',
  'The flower beds in the middle of the new roads are mine. I plant them twice a year.',
  'The marigold needs the sun, and the roses need the care. The ferns need nothing, and I love them for it.',
  'Water in the morning, not in the afternoon. The plants drink better when it is cool.',
  'The monsoon does half my job. The other half is weeding.',
  'This is a gulmohar, that is a neem, and the one over there is a jackfruit. Do not climb it.',
  'The lawn in front of the Administrative Building is cut every week. The director notices.',
  'The flag lawn is the proudest bit. A flag deserves a good lawn.',
  'We plant the flowers in rows, and the students plant their feet in the middle.',
  'The ashoka trees are tall and slim. They look like soldiers in a row.',
  'I plant a tree for every tree that is cut. It is a rule, and also a habit.',
  'The hill has a forest I do not touch. It is the campus\'s lung.',
  'The View Point trail is wild, not a garden. The forest looks after itself, and I only clear the path.',
  'The lotus in the lake blooms in the monsoon. Pink and white. Take a photograph.',
  'The reeds at the lake edge are the home of the birds. We leave them alone.',
  'The ducks like the lake grass. The students like the benches. The grass is not asked.',
  'The bougainvillea needs a lot of pruning. It is beautiful and a bit dangerous.',
  'The chrysanthemums are for winter. The cosmos are for the autumn. The lotus is for the rain.',
  'There are more than a hundred species of trees on the campus. I know most of them by name.',
  'The areca palm is tall and graceful. The coconut is taller, and the bamboo grows an inch a day.',
  'The banana plants near the hostel give fruit twice a year. The students are very quick to harvest.',
  'Mango season is in the summer. The raw mangoes disappear before they ripen.',
  'We grow the curry leaves for the mess. The leaves are the secret of the dal.',
  'The fountain at the Director\'s house is the most watered thing on the campus.',
  'The roundabout flower beds change colour with the season. Yellow now, red next month.',
  'The median on the new roads has small trees and flowers. The cars see them for a second, the cyclists for longer.',
  'I put a small tree every ten metres in the median. In five years the road will be a green tunnel.',
  'We use the compost from the leaves. It is good for the soil and for the budget.',
  'Please do not pick the flowers. A flower is happier on the plant.',
  'The students take photographs in the flower beds. I do not mind, as long as they do not step on them.',
  'Gardening is a quiet job. The plants do not argue.',
  'The ants are my enemy and my friend. The termites are only my enemy.',
  'I water the plants from the lake in the dry season. It is good water, and it is free.',
  'The soil here is red and rich. Everything grows, even the weeds.',
  'The hardest plant to grow is a lawn that students will not walk across.',
  'The new saplings need a guard of bamboo for the first year. After that, they are on their own.',
  'The Pronite stage has a garden behind it. It is for the artists, and for the peace.',
  'The Technology Park has a plaza with flower beds. I am designing the pattern.',
  'Orchids grow on the old trees. Do not disturb them, they are shy.',
  'The campus has a small nursery behind the workshop. The saplings are free for the departments.',
  'The best time to plant is just before the rain. The soil is ready, and the sky does the watering.',
  'Take care of the plants near the hostel. The first-year students plant a tree on the first day. Their tree is a good one.',
  'The rain brings out the frogs. I like the sound, the students find it noisy.',
  'I have a favourite tree. It is near the lake, an old banyan. It has seen more than I have.',
  'The lake view bench is under a big shade tree. I planted its grandfather.',
  'The solar lamps along the path are charged during the day. They are for the evening walks.',
  'The grass is cut short for the cricket ground and long for the lake bank. Each has a purpose.',
  'It takes a year to make a good lawn, and ten minutes to make a football pitch of it.',
  'Plants have moods. The roses sulk in the heat, and the ferns love the fog.',
  'The garden is a hospital for the soil. I am the nurse.',
  'My day starts at seven. I check the plants, I water the beds, and I talk to the trees.',
  'The gardeners are many. The garden is bigger, and the weeds are the biggest.',
  'We are going to plant more flowers near the lake circle. The air quality board is there. Green helps.',
  'I take the cuttings home. My own garden is small, but it is full of the campus.',
  'The pots at the doors are watered every day. The students put their keys in them.',
  'The roses near the guest house are for the visitors. They sometimes ask for a flower, and I say yes.',
  'The temperature goes up, and the pots go dry. I carry the water all day in summer.',
  'The campus has a good drainage. The rain goes where it should, and the garden is happy.',
  'The fog in January is lovely, and bad for the plants. A frost can kill the new ones.',
  'I wear a hat, and the plants wear dew. We are both ready for the day.',
  'The hibiscus is the most generous. It blooms all year, whatever the weather.',
  'The garden is a school. Every plant teaches patience.',
  'I put a small bench in the garden, and now the students sit there to study. I do not mind.',
  'The best thing about gardening is when someone smiles at a flower.',
  'The first-year students think a weed is a flower. I do not correct them.',
  'The elephant ear plants near the lake are as big as umbrellas.',
  'We plant a new tree for each batch that graduates. The trees are the real alumni.',
  'The soil needs rest. So do I. We take a break in the afternoon.',
  'If you see a small plant growing in a crack, leave it. It had a long journey.',
  'Birds nest in the trees near the library. I trim around them, and the birds thank me, loudly.',
  'The two-lane roads have a flower bed in the middle. I water them from the tanker at dawn.',
  'Be careful of the thorns. The roses have opinions.',
  'The little cactus near the entrance is the toughest thing on the campus. It has survived three cricket balls.',
  'I read about plants in the library. The librarian reserved a shelf for me. I am very proud.',
  'The monsoon is the best season. Everything grows, and I sit and watch.',
  'We are planting a bamboo grove near the lake. It will be a nice shade in a few years.',
  'Spring here is two weeks long, and glorious.',
  'On the first day of the rains, I just stand in the garden and breathe.',
  'The gardener\'s secret is simple: be patient, be kind, and carry a good hat.',
  'I feel proud when the campus is green. It is the best thing we can give to the visitors.',
];
