// What people say when you talk to them (E): lab staff, librarians, medical staff, children, international students, delivery
// riders, visitors, construction workers, auto drivers, staff families and research scholars.

export const lab = [
  'The lab closes at half past five. Finish your readings and clean the bench.',
  'Safety goggles on inside the chemistry lab!',
  'Please sign the log book before you start. Date, time, name, experiment.',
  'The fume hood is on. Do not open it halfway, the fumes go where they like.',
  'No food in the lab. Not even a biscuit. The ants have their own research programme.',
  'Wear closed shoes. A dropped beaker finds your toe every time.',
  'Tie your hair back near the burner. I have seen things.',
  'The balance is sensitive. Close the doors, and do not lean on the table.',
  'Read the experiment before you come. The lab is not the place to read it for the first time.',
  'The glassware is counted at the end of the day. If you break one, tell me, it is no crime.',
  'The chemicals are labelled. If a label is missing, do not guess. Ask me.',
  'Waste goes into the right bottle. Acids in one, solvents in another, and nothing in the sink.',
  'The first aid box is on the wall. The eye wash is on the left. I hope you never need either.',
  'If you see smoke, switch off the gas and walk out. Then tell me. Not the other way round.',
  'Calibrate the instrument first. Always. A wrong zero ruins a good day.',
  'The oscilloscope is old, but it is accurate. It is you I worry about.',
  'The soldering iron is hot. It looks the same as when it is cold, so be careful.',
  'The machine in the corner is the pride of the department. Please do not touch it with wet hands.',
  'Write your readings in the notebook, not on your hand. You will need them later.',
  'Take three readings and average them. Four if you are not sure. Five if you do not trust the first three.',
  'The microscope has a good lens. Do not touch the glass. Wipe with the soft cloth only.',
  'The centrifuge must be balanced. Two tubes of the same weight, opposite each other.',
  'The cold room is at four degrees. Take a jacket if you need to stay long.',
  'The server room is cold and noisy. The only place where the fan wins every argument.',
  'The workshop is next door. If you need something cut or turned, ask the technician politely.',
  'The 3D printer is in the corner. It takes six hours to print a small part. Plan for it.',
  'The best experiments fail the first time. The notebook with the failure is worth more than the one without.',
  'We have a spare set of reagents for the practicals. Ask before you start, not when you run out.',
  'The power cuts are short. The UPS is for the computers, not for the heater.',
  'The lab assistant is always there at nine. The professor comes at ten. The students come at ten past.',
  'The practical exam is next week. Come in the afternoon and practise. I will help.',
  'I have worked in this lab for twenty years. I have fixed most things with a screwdriver and some patience.',
  'The old oscilloscope was here before the department. It will be here after.',
  'Please do not take the stool from the other bench. We count the stools.',
  'The key to the cupboard is with me. The key to success is with you.',
  'The data you collect today is a part of a larger project. Thank you for being careful.',
  'The computer in the corner is slow. Do not save your work on the desktop.',
  'The printer is out of paper. The paper is in the cupboard. The cupboard is locked. I know.',
  'If the lights flicker, wait a minute. They always come back.',
  'We keep a small garden of cacti on the window sill. They need no care and they love the sun.',
  'We have a fish tank in the biology lab. Do not tap the glass. The fish have exams too.',
  'The chemistry lab smells different every day. Yesterday was vinegar. Today is something I will not name.',
  'The physics lab has a pendulum that has been swinging since the morning.',
  'Please switch off the equipment when you leave. The electricity bill is not a game.',
  'The microscope slides are in the drawer. Handle them like they are made of glass. They are.',
  'The cables are labelled. Put them back where you found them. The next group will thank you.',
  'The fire extinguisher is by the door. I hope it only ever gets dusty.',
  'The lab coat is mandatory. A white coat makes everyone look like a professional. Even you.',
  'Here is a spare pair of goggles. They are a little scratched, but your eyes are not.',
  'Do not point the pipette at anyone. I mean it, I have seen it happen.',
  'Wash your hands before you leave. Chemistry stays on the skin.',
  'Do not run in the lab. Walking is fast enough.',
  'The student in the corner has been here since morning. Not because of the experiment, but because of the air conditioner.',
  'We have a visiting scholar from another country. She says our lab is cleaner than hers. Do not tell the others.',
  'The vacuum pump is loud. That is normal. A silent pump is the problem.',
  'The thermometer reads two degrees low. Add two. Do not ask why.',
  'You can use the instrument after the fourth hour. Book it on the sheet.',
  'The sheet is on the door. The booking is first come, first served. Not first yelled.',
  'The electronic components are in the box. Ask for the resistor, not for the whole drawer.',
  'The motor is hot. Give it a minute before you touch it.',
  'We make our own solutions. Wear gloves, even for the water.',
  'If you spill something, stop. Tell me. Then we clean it together.',
  'The experiment today is short. The report is long. That is the usual ratio.',
  'The lab manual is a good start. The rest is your own mistakes.',
  'There is a notice board near the door with the schedule. Read it before you ask me.',
  'I am happy to help, but I will not do your experiment for you.',
  'Please do not take photographs of the equipment unless I say so. Some of it is for a project.',
  'Our lab was visited by the school children last week. They asked the best questions.',
  'The air conditioner is for the instruments, not for the people. The people are lucky to share it.',
  'The monsoon humidity affects the balance. We put silica gel next to it.',
  'The best time to work is the morning. The afternoon is for the report.',
  'The students\' projects are in the cupboard. Some are works of art. Some are works of effort.',
  'The final-year students stay late. I stay later. We understand each other.',
  'The key words of a good experiment: plan, measure, repeat, record, clean.',
  'I do not mind the noise, as long as it is the noise of work.',
  'The best discoveries happen when something goes wrong. Then you have to think.',
  'The lab is a place to make mistakes. Do not make them twice.',
  'I like it when the students ask why. The instruments never do.',
  'If you need extra time, ask in advance. I will see what I can do.',
  'Everything on this table is calibrated. Please do not move it, even a little.',
  'Let me show you how to hold that. There is a trick, and it saves the wrist.',
  'The best tool in the lab is a good notebook and a sharp pencil.',
  'Thank you for cleaning your bench. You are my favourite student today.',
];

export const library = [
  'The library is open till two in the night. Silence inside, please.',
  'Return your books by the due date. The fine is two rupees a day.',
  'Your ID card is your library card. Show it at the counter and you can borrow.',
  'You can borrow books for fourteen days. Renew them from the OneStop app, if you are not too late.',
  'The reading room is on the ground floor. The silent floor is upstairs. The not-so-silent floor is the corridor.',
  'In the exam weeks we open the extra reading room. Come early to find a seat.',
  'No food or drink inside. A water bottle with a lid is fine, a cup of tea is not.',
  'Please keep your phone on silent. A ringing phone is a social crime here.',
  'The new arrivals are on the shelf near the entrance. The best ones go quickly.',
  'We have the journals in the next section. The old issues are bound and kept in the basement.',
  'The newspaper corner has the daily papers and a few magazines. The crossword is already done, by somebody.',
  'The computer terminals are for the catalogue and for research. Not for the games.',
  'The photocopier is at the back. Two rupees a page. The paper tray is empty on Mondays.',
  'If you cannot find a book, ask me. The catalogue is good, but I am better.',
  'The reference books cannot leave the library. You can read them as long as you like.',
  'Lost a book? Tell us before the fine grows. A lost book costs its price and some patience.',
  'Do not write in the books. Use a notebook. A pencil mark takes an hour to erase, and I will find it.',
  'Please do not reserve seats with your bag. A seat is for a person.',
  'The best seats are by the window with the plug. Come at nine and you may get one.',
  'We close at two. The last borrowing is at half past one. After that, it is a locked door.',
  'Sunday hours are a little shorter. Check the notice at the entrance.',
  'The library was named after a great Assamese writer, Lakshminath Bezbaroa. His portrait hangs near the stairs.',
  'We have a good collection in Assamese literature. Ask for the short stories.',
  'We have books in Hindi, Bengali and a few other languages. Many students surprise themselves.',
  'The textbooks are in the front. The novels are at the back. The students go to the back first.',
  'Previous years\' question papers are in the bound volumes. Many students look, few admit it.',
  'The thesis shelf is the most serious. The titles are long and the covers are plain.',
  'The magazine rack has the monthly issues. The pictures are good, even if you do not read the text.',
  'The reading list for your course is at the counter. Take a copy.',
  'The inter-library loan takes a week. Ask early. Do not ask on the day of the exam.',
  'There is a locker for your bag. Take the key and return it. Do not take it to the hostel, again.',
  'The air conditioning is cool, and the chairs are comfortable. This is a dangerous combination for the students.',
  'We have seen students sleep here with an open book as a pillow. We pretend not to see.',
  'The group study room can be booked. Four people, one table, one whiteboard.',
  'The silent room is for individual study. If you whisper, I will hear you.',
  'The rule is simple: do not disturb. Everything else is detail.',
  'If you see a book on the wrong shelf, leave it on the cart. We will put it right.',
  'The library has more than a lakh of books. I have not read them all, but I know where they live.',
  'My favourite section is the old maps. Come, I will show you the campus before it was built.',
  'The old photographs of the campus are in the cabinet. The lake was smaller then, or the trees were.',
  'The digital library is open day and night. The login is in the OneStop app.',
  'You can read journals online from any hostel. The password is your roll number. Do not tell anyone.',
  'We organise a book fair every year. The students come for the discounts and leave with the novels.',
  'The book club meets on Fridays. We discuss the books, and the snacks.',
  'Every semester we buy the books that the faculty recommend. If you have a suggestion, write it in the register.',
  'I have worked here for fifteen years. I know the books, and I know the students who read them.',
  'The best time in the library is the late evening. The lamps are warm and the lake is dark.',
  'The students who study here at night become friends. I call them the owls.',
  'The quiet is a gift. Guard it.',
  'Some students come only to charge their phones. I do not mind. They sometimes read the first page.',
  'If you borrow a book for a project, tell the professor. He may have a copy.',
  'There are a few rare books in the locked cupboard. You may see them with permission.',
  'If a page is torn, tell me before you return it. Honesty is repaired faster than paper.',
  'We have a collection of the student magazines going back to the first batch. They are funnier than the textbooks.',
  'The library has a small cafe nearby, the lemon tea stall. Their tea is the reason the owls survive.',
  'Please do not bring the stall tea inside. I can smell it from here.',
  'If you need a quiet corner for a call, go outside. The corridor is for the phones.',
  'A tip: books on the second shelf from the bottom are borrowed the least. They are often the best.',
  'I have a soft spot for a student who returns a book on time. And a bigger one for the one who returns two.',
  'The students\' favourite book this year is the thickest one. We do not know why.',
  'Reading is the only kind of travel that does not need a ticket.',
  'The scanner is free. Use it for your notes, not for the whole textbook, please.',
  'The wireless internet works near the windows. The signal is weak in the stacks.',
  'Tell me the topic and I will point out three books. You will like one of them.',
  'The shelves are ordered by a number. It is a system, and you will love it by the end of the semester.',
  'The dictionary is on the table. Please put it back. I know it is heavy.',
  'The newspaper reading stand is the oldest furniture. The professors still use it.',
  'We are going to have a new section for design and art. The department asked for it.',
  'Please keep your feet off the chairs. They are not that kind of furniture.',
  'The photo of the library on the wall is from the first year. The building is the same, the trees are taller.',
  'Library week is in the autumn. We have talks, a quiz and a lot of cake.',
  'Do read something outside your subject. It is good for your own subject.',
  'A day without reading is like a day without tea, said a student. I made it a poster.',
  'Take care of the books. They are older than you, and they will outlive you.',
  'In the exam period we do not allow bags inside. Keep a small notebook and your card.',
  'The most borrowed book is a thick one on algorithms. The second is a short one on how to study.',
  'If you need a book that we do not have, tell me. I will try to get it.',
  'I have a favourite spot to read: the sofa near the south window. If you see me there, I am off duty.',
  'The students here are very polite. Even the ones who return the books late.',
  'The monsoon brings the smell of old paper. I like it.',
  'The best thing about a library is that everyone is quiet and no one is lonely.',
  'The library is a calm island in the middle of a busy campus. Please keep it that way.',
  'Visit again. The books will wait.',
];

export const medical = [
  'Drink plenty of water, it is humid today.',
  'The OPD is open till five. The emergency is open all day and all night.',
  'Please bring your ID card to the hospital. We need it for the record.',
  'If you have a fever for more than two days, come in. Do not wait for it to become a story.',
  'Take the medicine after food. On an empty stomach it only gives you a second problem.',
  'The pharmacy is on the ground floor. It is open until nine at night.',
  'Many students come with a stomach upset after exam week. Eat on time and sleep.',
  'Mosquitoes bite most near the lake at dusk. Use a net, a cream, or just a long sleeve.',
  'The monsoon brings colds and viral fevers. Keep your hair dry and your windows closed.',
  'Wash your hands before eating. It is old advice, and it still works.',
  'A cough that lasts more than two weeks needs a doctor. Not a cough syrup from the market.',
  'The ambulance is on call day and night. In an emergency, call the Security, they will send it.',
  'The ambulance gives way to nobody and everybody gives way to it. Please move aside.',
  'If someone faints, lay them down, lift their legs, and call for help. Do not give them water at once.',
  'A cut? Wash it with clean water first. Then come in for a dressing.',
  'A sprained ankle: rest, ice, a bandage, and a few days off the cricket field.',
  'We have a counsellor on Tuesdays and Thursdays. It is free, it is private, and it helps.',
  'Stress is real. A walk by the lake is not a cure, but it is a good start.',
  'Do not skip meals before the exams. A hungry brain does not remember.',
  'Take your medicine on time. The doctor does not mind, but the infection does.',
  'The blood donation camp is in the autumn. If you are healthy, please give. It helps a stranger and it feels good.',
  'Check your weight and blood pressure here once in a while. It is free, and it takes a minute.',
  'The doctors are on duty in shifts. The night doctor is the most patient.',
  'The nurse will see you first. She is the one who knows where everything is.',
  'Please wait in the line. The sickest are seen first, and not by who is the loudest.',
  'Report any allergy before you take a new medicine. It is important.',
  'The dentist comes on Wednesdays. Brush twice a day and he will not see you.',
  'The eye check-up is on Fridays. If you read in the dark, I know.',
  'We keep medicines for the common problems: fever, cold, stomach, a small injury.',
  'For the serious cases, we send the patient to the hospital in the city. The ambulance is ready.',
  'Ice and a rest are good for the sports injuries. Do not play through the pain.',
  'A cold is a cold. It goes in a week. With medicine, in seven days. Without, in a week.',
  'Please do not take antibiotics without a prescription. The bugs are cleverer than you think.',
  'A glass of warm water with lemon and honey is a good start for a sore throat.',
  'Gargle with warm salt water. It is not glamorous, and it is effective.',
  'Sleep is the best medicine. Eight hours, if you can. Seven, if you must.',
  'If you have a headache, drink water first. Then lie down. Then call me.',
  'Walking is the best exercise. The campus is made for it.',
  'Do not run if you have a fever. The cricket final can wait, the hospital cannot.',
  'We saw many sunburns in the summer. Use a cap, or take the shade.',
  'In winter the fog is cold and wet. A shawl is a very good idea at six in the morning.',
  'If a dog bites you, wash the wound with soap and water, and come at once. We have the injections.',
  'If you see a snake, stay still and walk away slowly. Then come and tell us the colour.',
  'Bring your own water to the View Point trail. It is a long climb and the sun is stronger than you think.',
  'If you get a blister, do not pop it. A plaster and a good pair of shoes.',
  'The first aid boxes are in every hostel and the guard cabins. Know where yours is.',
  'The health card is in the OneStop app. It keeps your appointments.',
  'A healthy diet is simple: vegetables, fruit, water. And the occasional thali.',
  'Many students skip breakfast and then complain about the lecture. Eat something.',
  'Please do not share medicines. What worked for your friend may not work for you.',
  'Sit up straight in the study chair. Your back will thank you in ten years.',
  'Take a break from the screen every hour. Look at the lake, or at a tree.',
  'Eye strain is the most common complaint in the exam season. The cure is a break and a bit of sunlight.',
  'The campus hospital treats the students, the staff and the families. We know many of you by name.',
  'The staff children get their vaccines here. The little ones are brave. The big ones are not.',
  'The oldest patient I treat is ninety. The youngest, three days.',
  'If you are worried, come. A small worry is easier to treat than a big one.',
  'The pharmacy has a few Ayurvedic medicines too. Ask the pharmacist.',
  'Do not take the medicine from the market on the advice of a friend. Ask us first, the advice is free.',
  'The waiting room has magazines. Some are older than the building.',
  'I enjoy my work. People come in with a worry and go out with a smile. Most of the time.',
  'The monsoon is the busy season. The dengue cases rise, and so does our alertness.',
  'We run a campus cleanliness drive each year. Clean water, clean food, and no stagnant puddles.',
  'The best preventive medicine is hygiene and a good night\'s sleep. The rest is luck.',
  'If a friend looks very low, talk to them. Do not leave it to the weekend.',
  'Ask for help early. It is a sign of strength, not weakness.',
  'The ambulance driver is a hero. He has the shortest route to every hostel in his head.',
  'I wish all the visitors a pleasant stay, and no need for our services.',
  'If you meet a doctor in the corridor, say hello. They do not get many hellos.',
  'The campus has a dog that visits the hospital every morning. We call him the unofficial vet.',
  'Be kind to the staff. We have long shifts, and a smile makes them shorter.',
  'The hospital is quiet at night. Sometimes the quiet is the best medicine.',
  'The cleaning staff do a brilliant job here. A clean ward is half the treatment.',
  'Have a glass of buttermilk in the afternoon. The campus heat is a good enough reason.',
  'The best way to stay healthy: walk, sleep, eat, laugh. In that order, or any.',
  'Do not hesitate to call. I would rather be called for nothing than not called for something.',
  'The more you smile, the quicker the doctor sees you. I am joking. A little.',
  'Please follow the advice and take the full course of the medicine. Half a course is a bad plan.',
  'Come back for a review in a week. I will see how you are.',
  'Keep well, and keep the lake in your evening routine.',
];

export const kid = [
  'Bhaiya, will you play cricket with us?',
  'We have a holiday tomorrow!',
  'I can ride my cycle without hands!',
  'Didi, do you want to see my drawing? It is a rhino.',
  'I go to the school here. My teacher is very strict, but she gives stickers.',
  'My dad works in the lab. He says it is not boring, but it looks boring.',
  'We are playing hide and seek. You can hide, but not behind the tree. That is my tree.',
  'I saw a big dog yesterday. It was so big. It was this big!',
  'There is a monkey near our house. It took my mother\'s banana.',
  'Do you want to see my cycle? It has a bell. Listen. Ting-ting!',
  'I like the swings in the park. I can go higher than my brother.',
  'The ice cream man comes at five. I always get the orange one.',
  'My grandmother lives with us. She tells me stories of Assam.',
  'The rhino at the circle is my favourite. Do you know it is a mother and a baby?',
  'I want to be a pilot. Or a scientist. Or both, with a cricket bat.',
  'My school bus is yellow. It goes through the Main Gate every morning.',
  'In school we have a garden. I planted a tomato. It is red now!',
  'My friend is called Mintu. He is faster than me, but I am cleverer.',
  'When it rains, we jump in the puddles. Mother says no, but she smiles.',
  'I know the way to the lake. My father takes us on Sundays for the boats.',
  'I rowed a boat once. It went round and round. Father laughed.',
  'The ducks near the lake are funny. They go in a line, like school.',
  'Can you play with us? We are one short on the team.',
  'I know all the hostel names. Manas, Lohit, Dihing, Brahmaputra... shall I say all fifteen?',
  'The big students are nice. They give us biscuits when we ask politely.',
  'Please do not tell my mother that I climbed the tree.',
  'I have a new notebook. It has a tiger on it.',
  'I know a secret place near the lake. It has a hole in a tree. I cannot tell you where.',
  'We make paper boats and float them in the drain after the rain.',
  'My sister is in class six. She says I talk too much. I do not talk too much.',
  'There is a guard near our gate. He gives us a salute every morning.',
  'The market has the best jalebi. I like it with the little paper bag.',
  'My cricket bat is new. It is from the shop in the Market Complex.',
  'I want to see the View Point, but it is very far. Father says when I am ten.',
  'We had a picnic by the lake. We forgot the spoons, so we ate with our hands.',
  'I won a race at school. It was a skipping race, and I skipped the fastest.',
  'The school has a big playground. We have an assembly there, and everyone sings.',
  'My favourite fruit is a mango. Raw, with salt and chilli.',
  'My favourite colour is yellow, like the bus.',
  'The lights on the lake look like stars. I like them.',
  'Do you know why the sky is blue? My teacher said it is because of the light.',
  'My brother fixed my cycle chain today. He is the best brother in the world, but do not tell him.',
  'We went to the temple last Sunday. I ate all the prasad.',
  'I saw a snake near the hill. It went away when I shouted.',
  'My mother makes the best pitha. You can come if you bring a plate.',
  'I help my father water the plants. He says I am his best gardener.',
  'There is a puppy near our house. I call him Moti. He follows me to school.',
  'I like it when the Pronite music comes from the ground. It is like a big party for everyone.',
  'My friend\'s father is a professor. My friend knows the answers, but he does not tell me.',
  'We have a cricket match every evening. I always field at long on, because I am very good at it.',
  'My teacher says I should read more. I read the cartoon books. They count.',
  'Look, I can do a handstand!',
  'The tall tree near our house has a nest. I saw the eggs.',
  'The pool is only for grown-ups, mostly. I can swim a little, with the float.',
  'The bus stop is where all the big buses start. I saw four of them.',
  'The people at the gate are nice. I wave, and they wave back.',
  'My favourite part of the day is the evening, when the whole campus comes out to play.',
  'I like the rain. The frogs come out and sing.',
  'I want a dog. Mother says we have no space. I say the campus is the space.',
  'My dad says the campus has more trees than people. I counted ten trees today.',
  'I know how to say hello in Assamese. Nomoskar!',
  'I know how to say thank you in Assamese too. Dhonyobad!',
  'The school has a library with a corner for little kids. The pictures are bigger than the words.',
  'I made a friend today. His name is Arun. He has a red cycle.',
  'I have a torch. It makes shadows on the wall. I made a dinosaur.',
  'We play near the flower beds, but we do not step on them. The gardener told us.',
  'I helped the gardener plant a tree. It is small, but I will see it grow.',
  'The students have a big cycle shed. It has a roof with solar panels. I looked at it for a long time.',
  'I can count to a hundred. Shall I count?',
  'The big students play guitar in the evening. I sit near them and listen.',
  'I have a pet fish at home. It is called Goldie. It is not gold, it is orange.',
  'Mother says do not go near the lake alone. So I go with my friend.',
  'My shoes have lights. They blink when I run. Look!',
  'We saw a rainbow yesterday after the rain. It was a double one.',
  'Can you tell me a story? I like the ones with dragons.',
  'My cousin visits at Bihu. We dance together, and she is better.',
  'My favourite game is tag. I am always the one who is caught.',
  'We have a trampoline at school. I jump higher than the teacher.',
  'It is too hot today. Can we go to the shade and drink a cold drink?',
  'The little bird in the tree is singing. Can you hear?',
  'I have a loose tooth. Look. It wobbles.',
  'My father is a professor. When I grow up, I want to be a professor of cricket.',
  'I like the campus. It is like one big garden with houses in it.',
  'I will be a doctor and I will give everyone sweets instead of injections.',
  'Bye bye! I have to go. My mother is calling for dinner.',
];

export const intl = [
  'Hi! I am here on an exchange. The campus is so green!',
  'I love the momos at the market.',
  'The monsoon here is something else.',
  'Everything is so friendly. People greet me even when they do not know me.',
  'I am learning some Assamese. Nomoskar, and dhonyobad. Is that right?',
  'The tea here is fantastic. We have the leaves at home, but not this taste.',
  'My home country is very far. The campus makes me feel less far.',
  'The food is spicy! I am learning to ask for less chilli. Is "kom jhal" correct?',
  'The bicycles are a very good idea. At my university, we only walk.',
  'I took the boat on the lake. The speedboat was fast, but the rowing boat was fun.',
  'I saw the sunrise from the View Point. The mist over the river looked unreal.',
  'The trail to the View Point is beautiful. The forest is so dense. I kept looking for monkeys.',
  'I stay in the guest house by the lake. At night I hear the frogs, and in the morning, the birds.',
  'I am in the research group of a professor here. They are very helpful and very patient.',
  'In my country, the library closes at ten. Here it is open until two in the morning! I am shocked.',
  'The mess is interesting. I eat with my hands now. It is the right way.',
  'The Sunday special thali is my favourite meal of the week.',
  'There are many festivals here. Alcheringa was incredible. I danced for three hours.',
  'Techniche was impressive. The robots, the talks, the energy.',
  'I met a student from the Bihu club. She taught me the steps. I am still learning.',
  'The campus is a very safe place. I walk at night, and nobody bothers me.',
  'People here are very curious about my country. They ask me many questions.',
  'I like the elephants in the stories. I have not seen one here yet, only a rhino statue.',
  'The rhino statue at the circle is a good photo spot. Every visitor takes one.',
  'The roads are quiet, but the cyclists have strong opinions about the bell.',
  'I am surprised by the number of dogs. They are all so calm and friendly.',
  'I feed the cats sometimes. A friend told me it is not good. I give them only a biscuit.',
  'I can buy everything with my phone here. At home I still carry coins.',
  'I like the signs in two or three languages. They look like a poem.',
  'The Main Gate is so beautiful, the stone with the three scripts. I love it.',
  'The students invited me to dinner at their hostel. I brought a gift, and they laughed. It was a good laugh.',
  'My roommate is from Odisha. We talk about rice, and cricket, and rice.',
  'I find the weather here a bit hot, a bit wet and very green.',
  'I use the campus bus every day. It starts from the new bus stop and it is always on time.',
  'The pool is great. I swim in the morning, before the heat starts.',
  'I attended a lecture in the big hall. The professor was very good, and the students asked many questions.',
  'The conference was very well organised. I met researchers from many countries.',
  'I take a walk along the lake in the evening. It is the best time.',
  'The students here are very hard-working. They study late and then play cricket at midnight.',
  'I tried the paan once. It was an experience. I will not try it twice.',
  'The gamosa is a beautiful cloth. I bought three as gifts.',
  'I bought a small cycle bell. It sounds very Indian.',
  'My university has a partnership with this one. I am the first student on the programme.',
  'I think the campus is quieter than any other place I have lived. I like the quiet.',
  'I want to visit Kaziranga. They say the rhinos are real. Not statues.',
  'I want to visit Majuli. A river island with a monastery, I heard.',
  'I want to see the Brahmaputra at sunset. It must be wide and slow.',
  'I like the monsoon music. The rain on the tin roof is a symphony.',
  'My family calls me every evening. They ask if I am eating well. I say yes, I am eating very well.',
  'The institute is very large. I got lost on the first day. A kind student walked me to my building.',
  'The signs are in English, so it is easy for me. The people speak so many languages, it is wonderful.',
  'I am learning to cook rice the Assamese way. My teacher is a friend from the mess.',
  'The mess cook gave me an extra sweet. I am not sure why. I think he likes my accent.',
  'I like the flowers in the middle of the new roads. Where I come from we have only concrete.',
  'The green bike lane is a very good idea. I felt very safe on my cycle.',
  'The students have so many clubs. I joined the photography club and the chess club.',
  'The festival of lights was wonderful. The hostels were shining.',
  'I had a fever, and the hospital helped me quickly. The doctor was kind, and the medicine was cheap.',
  'The post office at the KV Gate is where I send my postcards. They are slow, but the stamps are pretty.',
  'I met an Indian professor who studied in my city. The world is small.',
  'The air quality board near the lake is interesting. I check it every morning.',
  'I find the number of people on the roads in the evening amazing. Everyone is outside!',
  'I love the street food. The Khokha market has the best snacks.',
  'I am taking a course on design. The final project is on the campus signage.',
  'Everybody is so helpful. If I ask for directions, three people walk me there.',
  'I like the old trees. They are bigger than anything we have at home.',
  'The campus has a good internet connection. Not perfect, but good enough to call home.',
  'I am practising my Hindi. The students laugh, and then they teach me.',
  'My supervisor takes me for tea every Friday. It is the best meeting of the week.',
  'I do not need a heavy coat here, but I need a good umbrella.',
  'There are so many shades of green here. I have counted fifteen.',
  'The nights are very dark. The stars are very bright.',
  'People take their cycles everywhere, even to the lecture. I do not understand how they find them again.',
  'I love the cultural nights. The music, the lights, and the crowds. It reminds me of a big family.',
  'I am impressed by the facilities: the library, the labs, the gym.',
  'I love that people say good morning to strangers. In my country that is unusual.',
  'My plan is to stay for a semester and maybe stay longer. The campus makes it easy.',
  'I think the campus is a small world. A world with a lake.',
  'Thank you for talking to me. It is nice to meet someone who has time.',
];

export const delivery = [
  'Order for your hostel? Please tell me the OTP.',
  'Traffic at the Main Gate today, sorry for the delay!',
  'I have a parcel for the Brahmaputra hostel. Do you know which gate is near it?',
  'The guard does not let me in, so the student has to come down. It is the rule.',
  'If you ordered the food, please come to the gate. It is getting cold.',
  'What is the OTP? Four digits, it is on your phone.',
  'I know all the hostel names now. Manas, Lohit, Dihing, Kameng. But the rooms, I cannot.',
  'The roads here are better than in the city. No potholes, and good shade.',
  'I come here ten times a day. The guards know me, and so does the dog at the Khokha Gate.',
  'It rains, I deliver. It is hot, I deliver. It is Sunday, I deliver more.',
  'The first of the month: a lot of orders. The students got their pocket money.',
  'The exam week: a lot of orders. Nobody has time to go to the mess.',
  'Midnight orders are the best tips. The students are grateful, and a little hungry.',
  'Please give a good rating. It is my job, and I like it when someone says thank you.',
  'I cannot go beyond the gate after ten. The rule is for everyone.',
  'The Khokha Gate closes at ten. If you order after that, I will have to come around by the Main Gate.',
  'The Main Gate is open all night. It is a long way around, but I know a shortcut.',
  'I use the cycle lane. The new roads are good for the bikes. I feel safe.',
  'My phone says I am at the gate. My eyes say I am at the wrong gate.',
  'Hello, sir. Your order is two noodles and one cold coffee. Is it you?',
  'If I cannot find you, I call. Please pick up. The phone is not for the games.',
  'The students always say they are near. They are never near.',
  'I like this campus. It is quiet, and the students say thank you.',
  'A student gave me a tea once. It was cold outside, and it was the best tea of my life.',
  'I wait at the stop near the gate. The shade is good, and the guard is friendly.',
  'The delivery is a job with a lot of walking. Not here, here I ride.',
  'I know the campus roads well. The two-lane ones are quicker, but the old ones are prettier.',
  'The traffic circle near the lake has a guard waving. I wave back.',
  'If the order is for the girls\' hostel, I give it to the guard. They send someone down.',
  'I take small breaks near the lake. Five minutes, a glass of water, and then back to work.',
  'The bag is hot. Please take it before it gets cold.',
  'Please check the order before I leave. I will wait.',
  'The roads are slippery in the rain. I go slow, and the food goes cold, but I stay safe.',
  'The monsoon is difficult. The orders double, and the roads double in water.',
  'Sometimes the app sends me to the wrong hostel. Then I ride to the right one and say sorry.',
  'The best order of the day is the one that is paid in cash and has a tip.',
  'I started this job to pay for my studies. I am in the second year of college.',
  'My brother also delivers. We meet at the gate for lunch.',
  'I like it when the guards are friendly. The ones who smile are the best.',
  'It is a long day. I start at ten and end at midnight. The tea keeps me going.',
  'I love the evening here. The lights come on, and the lake is beautiful.',
  'If you see me on the road, give me space, please. I carry a bag on the back, and the bike is tired.',
  'I am not allowed to wait too long. The app counts every minute.',
  'Do you know the way to the Technology Park? A new order, a new place.',
  'The Technology Park has a plaza with flowers. I stopped for a minute, to look.',
  'The new bus stop is a landmark. I use it to find my way now.',
  'I feel safe here. The guards, the lights, the cameras. It is a good place to work.',
  'If I am late, I am sorry. The traffic is not an excuse, but it is the reason.',
  'It is a big campus. The distance between the gate and the hostel is a ride of ten minutes.',
  'The students here are polite. In some places, they just snatch the bag.',
  'If you want, I can wait while you take it to your room. But please be quick.',
  'The parcel is a gift? Very nice. Whoever it is for is lucky.',
  'The tracking says I am five minutes away. The tracking is optimistic.',
  'Please keep the packet with the helmet. The rain gets in.',
  'The gate pass is checked at the Main Gate. I show my card and they let me in.',
  'My shift ends at midnight. The last order is always the hardest.',
  'The cold drink is melting. Take it now, please.',
  'I know a shortcut near the lake. The road is narrow, but it saves two minutes.',
  'I have to be careful with the speed limit. Thirty on campus, and the cameras are watching.',
  'The best part of the job is the speed. The worst is the helmet in the heat.',
  'When the festival is on, the whole campus orders food. We are very busy.',
  'During Alcheringa the gates are crowded. We take the side gate, but it is only for the staff.',
  'My bag has a thermal lining. The food stays hot for an hour. It is an hour I do not have.',
  'I hope you enjoy the food. Do give a good review.',
  'Do you want a receipt? I can show it on the phone.',
  'If it is the wrong order, tell me. I will call the restaurant.',
  'This is a good campus. The people say thank you, and the dogs do not chase my bike.',
  'The dogs here are friendly. At other places, they run behind the bike. Here they just look.',
  'At night the road to the hostels is dark in some parts. I use a torch on the bike.',
  'Please do not tell the guard I was late. He keeps a note.',
  'I have a long list of orders. If you see me running, it is because I am.',
  'I like the weekend. Fewer orders, more tea.',
  'I am from the town nearby. I know the roads and the people, and the campus is part of my day.',
  'The campus is the cleanest place on my route.',
  'The leaves on the road are slippery. I ride slowly.',
  'Take a moment to smile at the person who brings your food. It matters.',
  'I use the app to find the way. Sometimes it takes me to a lake. I turn around.',
  'Sorry, I cannot take cash for the online orders. The app handles it.',
  'The students order the same thing every night. I know their habits, and they do not know my name.',
  'My name is on the bag. Look. Read it. Remember it. Thank you.',
  'Thank you. Have a good meal. And a good night.',
];

export const visitor = [
  'We came to see our son. What a beautiful campus!',
  'Where is the Administrative Building, please?',
  'We are here for the first time. Everything is so green and so quiet.',
  'My daughter is in the second year. She said the campus was beautiful, and she was right.',
  'We came for the convocation. We are so proud that we forgot to eat.',
  'We are staying at the Guest House. The lake view from the room is very good.',
  'Could you tell me where the hostels are? We are looking for the Manas hostel.',
  'We came by taxi from the airport. It took about an hour, and the road was pleasant.',
  'The Main Gate is very impressive. Three languages on the stone. We took photographs.',
  'Is it all right to take photographs here? I do not want to offend anyone.',
  'Is the lake open to the public? It looks lovely.',
  'We heard there is a trail to a viewpoint. Is it far?',
  'Is the trail to the View Point safe? We are not very young.',
  'We visited the library. It was so quiet, and so full of students.',
  'My son showed us the mess. The food was simple, and good.',
  'He is thinner than before. I am going to feed him as much as I can.',
  'The students are so polite. They say namaste to strangers.',
  'We are from Delhi. The air here is so fresh. My lungs are thankful.',
  'We are from Kolkata. The campus reminds us of a small town with a big heart.',
  'We are from a village near Jorhat. We have never seen such a big institute.',
  'We took the campus bus. It is free, and the driver was very kind.',
  'Is there a place to eat nearby? We are a little tired.',
  'The tea stall near the lake is where our son takes us. The tea is lovely.',
  'The market has everything. We bought a gamosa for our relatives.',
  'We attended a talk at the auditorium. It was very interesting. I understood half.',
  'My husband is a teacher. He says the library is wonderful.',
  'The campus is so clean. I do not see any litter.',
  'The cyclists are fast. We have to be careful to cross the road.',
  'The roads are lovely. The cycle lane is a good idea. The flowers in the middle are lovely.',
  'We saw the rhino statue at the circle. Our grandson wants to take one home.',
  'The guard was very helpful. He showed us the way to the Guest House.',
  'We went to the swimming pool. Our daughter swims, but we just watched.',
  'The lake is the most beautiful part. We sat there for an hour.',
  'We heard about the festivals. We hope to come for Alcheringa one day.',
  'We saw the cricket ground. Our son plays for the hostel team.',
  'There is a stage there now. It is permanent? Very good.',
  'The Technology Park is new, they told us. A park for start-ups. That is the future.',
  'We have a question. How do we get to the Technology Park from here?',
  'It is hot, but the trees help.',
  'We came in the morning and we are leaving in the evening. A full day.',
  'We want to see his room, but the guard says visitors cannot go up. I understand.',
  'We met his friends in the common room. They were so cheerful.',
  'He gave us a tour of the campus on cycles. I was afraid, but it was good.',
  'Is there an ATM nearby? We need some cash for the taxi.',
  'The ATM is at the Market Complex. Thank you very much.',
  'Do you know where the post office is? We want to post a letter.',
  'The post office is at the KV Gate, built into the wall. How convenient.',
  'We are here for a conference. The organisers have been wonderful.',
  'We attended the AI Confluence. The talks were fascinating. And the coffee, too.',
  'My wife wants to see the hospital. She is a nurse. She is curious.',
  'We stayed at the Guest House. The staff are so kind.',
  'We are here for the admission. My son is a bit nervous, and so am I.',
  'My daughter just joined. She cried when we left. I cried more.',
  'We are visiting a friend who works here. He says it is the best job.',
  'We have been planning this trip for a year. It was worth the wait.',
  'We are a group of teachers on a study tour. Your campus is a model.',
  'We are from a school. The children want to see the labs.',
  'Our children are on a school trip. They are so excited. And so loud.',
  'The students gave us a very warm welcome. We did not expect it.',
  'We were told that the campus has a very good bus service. It is true.',
  'My father used to teach here. He told me about the lake. It is more beautiful than he said.',
  'I came here as a student twenty years ago. It has grown a lot, but the lake is the same.',
  'The new buildings are good. The old trees are better.',
  'Could you take a photograph of us in front of the gate?',
  'I would like to see the Director, but I do not have an appointment.',
  'We are looking for the Dean\'s office. It is somewhere near the flag lawn.',
  'I found a bag near the library. Where should I give it?',
  'We have a taxi waiting at the gate. How long is it to walk?',
  'The sun is strong. Is there a shade nearby?',
  'The students here are brilliant, I am sure. They are also very hungry.',
  'We stayed for lunch. The mess was crowded, and the food was tasty.',
  'We saw a few dogs. They look well-fed.',
  'It rained suddenly. Everyone ran for cover. We found a bus shelter.',
  'We were caught in the rain near the lake. A student shared an umbrella. What a kind boy.',
  'Is it safe to walk here at night? We were told it is. We saw the lights.',
  'The guards here are polite. In many places they are rude.',
  'We are going to visit Kaziranga tomorrow. Have you been?',
  'I like the smell of the wet earth. I think it is the best part of Assam.',
  'The Brahmaputra is mighty. We went to see it from the bank. It took our breath away.',
  'We had a lovely time. Thank you for your help.',
  'We will come again. Next time, for the Pronite.',
  'Please tell the guard we said thank you.',
  'We are a bit lost. Could you point us to the gate?',
  'Goodbye, and may you do well. We are proud of all the students.',
];

export const worker = [
  'The new block will be ready next year.',
  'Construction till five, then home.',
  'Wear your helmet, please. The site is not a playground.',
  'The cement mixer is loud, but it keeps the work going.',
  'We lay about a hundred bricks an hour, if the sun is kind.',
  'The new building will have six floors and a lift. The lift is the part we are all waiting for.',
  'This site is for the Technology Park. The old cricket ground is gone, and the labs are rising.',
  'The plaza is the last part. First the walls, then the roof, then the flowers.',
  'My work starts at seven and ends at five. After that, the machines sleep.',
  'The monsoon slows us down. A wet brick is a heavy brick.',
  'We drink a lot of water here. The sun is hard on the head.',
  'We build in layers. The foundation, the columns, the beams, the slab, and then again.',
  'The steel is tied by hand. Each knot is a promise.',
  'The scaffold is made of bamboo and steel. The bamboo is stronger than it looks.',
  'We have a tea break at ten. It is a sacred time.',
  'The foreman is strict, but fair. He is also generous with the tea.',
  'I come from a village near Dhubri. I stay in the labour camp with my brother.',
  'My children are in school in the village. I send them money every month.',
  'I like working here. The campus is clean, the people are polite, and the water is good.',
  'The students sometimes stop and ask what we are building. I tell them, and they say wow.',
  'I like the 3D printer that made the cement guard post at the KV Gate. A machine that builds. Very clever.',
  'We use a lot of cement. The cement bags are heavy, and my back knows it.',
  'The crane is the biggest machine. The driver is a hero. He sits high and works long.',
  'Please keep out of the site. It is dangerous. Sorry, but the rule is the rule.',
  'The painters come last. They make the building look like it was always there.',
  'The electricians put in the wires. If you see a wire, do not touch.',
  'The plumber is the most important person. Without him, the building is only a cave.',
  'When the first student walks into the building, I feel proud.',
  'I helped build the stage near the cricket ground. The truss for the lights is as tall as a coconut tree.',
  'The lights are very bright. I saw them being tested at night. A whole ground in daylight.',
  'The old roads are being widened. The new ones have a median with flowers. We plant them.',
  'I made the cycle lanes. Green paint, all by hand. It is a long road.',
  'The painters made the zebra crossings. Very straight lines.',
  'I work with a team of ten. We know each other\'s habits, and each other\'s tea.',
  'The weather is the boss. If it rains, we stop. If it shines, we run.',
  'The heat in the summer is hard. We take a break at noon and work again at three.',
  'The winter is nice. The sun is soft, and the work is easy.',
  'In the monsoon the mud sticks to the boots. Every step is a workout.',
  'The sand and the stones come in trucks. The trucks come in a line, and the dust comes with them.',
  'We water the walls. It helps the cement to set well. A wall that is not watered is a wall that cracks.',
  'The bricks are made in a kiln near the river. Red and strong.',
  'I like the smell of a freshly poured floor. It smells like a new beginning.',
  'My uncle was a mason here when the first hostel was built. The hostel still stands.',
  'The campus has many buildings that I have worked on. I walk past them and I smile.',
  'The students are friendly. One of them taught me a few English words.',
  'We follow the plan. The plan is on the board. It is a big drawing, with many lines.',
  'The engineer visits every day. He looks, he measures, he nods. When he does not nod, we redo it.',
  'We have a safety briefing every morning. Helmets, boots, gloves. It is a good habit.',
  'We stop when the siren sounds. It is lunchtime, and the rice is waiting.',
  'My lunch is rice, dal and a pickle. The pickle is from my wife. It is the best.',
  'There is a small shop near the site that sells tea and biscuits. I go there often.',
  'The dog near the site is called Sheru. He guards the cement bags. He is a good dog.',
  'I do not mind the dust. I mind the noise. But the noise means work.',
  'The big machine digs a foundation in an hour. We used to dig it in a week.',
  'The best part of the job is the end of the day, when the building has grown a little.',
  'When the building is ready, there will be a ceremony. We stand at the back and clap the loudest.',
  'The bus stop terminus was a quick job. The platform and the roof went up in a month.',
  'I built a part of the Technology Park. My name is on no wall, but my hands are in all of it.',
  'The trees on the campus are protected. We never cut a tree. We build around it.',
  'We plant a sapling when we finish a building. It is a tradition now.',
  'The site is quiet on Sundays. Only the watchman and the dog.',
  'We have a day off each week. I spend it with my family on the phone.',
  'The wages are paid every Saturday. It is a big day for us.',
  'I have worked on three campuses. This one is the greenest.',
  'We use cranes and ropes. A simple pulley and a strong arm can do a lot.',
  'My son wants to be an engineer. I say, study hard. I will build the house for your degree.',
  'It is a long day, but when the building rises, it is a good one.',
  'Please be careful on the road near the site. The trucks are big and slow.',
  'Please give way to the mixer truck. It carries ten tonnes of concrete and does not stop easily.',
  'We cover the sand with a sheet in the wind. The students are thankful.',
  'We rent a small room near the market. Some of us stay on site.',
  'The campus gate guards check our passes every morning. They are strict, and nice.',
  'The best coffee is at the tea stall by the lake. We go there on Sundays.',
  'I do not know much English. But I know "thank you" and "welcome". They are enough.',
  'The new gate of the library will face the flag lawn. We worked on the doors.',
  'We turned the entrance around. Now when you come out of the library, you see the flag.',
  'The scaffolding comes down soon. Then you will see the real building.',
  'Everything has its time. The cement sets, the paint dries, the tea cools.',
  'Have a good day. Mind the wet floor.',
];

export const auto = [
  'Guwahati? Paltan Bazaar, two hundred.',
  'Airport? That will take an hour from here.',
  'Where to? I will take you there, quick and cheap.',
  'The fare to the city is not fixed, but I give a fair price.',
  'Sit down, sit down. Hold the rod when we turn.',
  'It is a long drive to Paltan Bazaar. About two hours in the traffic.',
  'The Saraighat Bridge is the way to the city. A long bridge over the great river.',
  'Do you want to go to the railway station? It is about an hour, and the road is good.',
  'The airport is far. A taxi is more comfortable, but the auto is cheaper.',
  'I wait outside the Main Gate. The students come out in the evening, and the good business begins.',
  'The students go to the city on Saturdays. The autos are full and the queue is long.',
  'I take them to the market, to the cinema and to the station. Some of them I take every month.',
  'Students always bargain. I always lose. But a good student is a good customer.',
  'The auto has a meter, but it is broken. So we talk.',
  'I have been driving an auto for fifteen years. I know every road, every pothole and every shortcut.',
  'The road from the campus is straight. A little hilly, but good.',
  'The monsoon is difficult. The roads fill with water, and the auto gets stuck.',
  'In winter the fog is thick. I drive slowly, and the passengers are quiet.',
  'In summer the auto is hot. I put a wet cloth on the head.',
  'My auto is green. It is a good colour, like the campus.',
  'I wash the auto every Sunday. A clean auto brings good luck.',
  'My brother has an e-rickshaw. He is allowed on the campus roads.',
  'The e-rickshaws run on the campus. They are quiet and cheap.',
  'The campus bus is free for the students. We do not compete. We go outside.',
  'The Khokha Gate is the way to the market. Ten minutes by auto, thirty by foot.',
  'The KV Gate is the way to the school. Many children come that way.',
  'Do you want a ride around the campus? I can give you a small tour. Twenty rupees.',
  'I know the campus too. I take the visitors for a ride. They like the lake.',
  'The lake is my favourite place. I stop there for a tea.',
  'I like the guards. They wave when I pass.',
  'The campus has a very good road. The new two-lane roads are the best I have driven on.',
  'The flowers in the middle of the road are very nice. They make me happy.',
  'Today is a slow day. Tomorrow will be busy.',
  'The convocation day is a big day. Parents, guests, everyone needs a ride.',
  'During Alcheringa the roads are full. I make a lot of trips, and go home late.',
  'During Techniche I take the guests to the station. They are very polite.',
  'If you want to go to the airport, book in advance. I will wake up at four.',
  'I can take you to Kamakhya temple. It is a nice trip. The hills, the river, the temple.',
  'I can take you to the Brahmaputra bank. It is a lovely place at sunset.',
  'The Umananda island is on the river. You go by boat. I take you to the ghat.',
  'The zoo is in the city. Many families go there on Sundays.',
  'The Fancy Bazaar is for the clothes and the cloth. The Paltan Bazaar is for the food and the electronics.',
  'The Dighalipukhuri park is a pleasant place. A lake in the city.',
  'My home is in North Guwahati. A few minutes from here.',
  'I have three children. The eldest is in the college, the youngest is in the school.',
  'This is a good job. I am my own boss, and the passengers are my teachers.',
  'My auto has a radio. I play old songs, and the passengers sing.',
  'I was a driver for a school bus before. Now I drive an auto. I like it better.',
  'Take care when you get down. The step is high.',
  'No need to hurry. I will wait for you.',
  'The road ahead is under repair. We will take a different way.',
  'I take the highway to the city. It is faster, but there is more traffic.',
  'In the rain, the auto is a boat. I jest, but not by much.',
  'The best time to travel is early in the morning. The roads are empty and the air is cool.',
  'The worst time is the evening. Everyone is going home, and so am I.',
  'I charge more at night. The roads are dark, and the passengers are few.',
  'If you need a receipt, I will write one. On the back of a cigarette packet, but I will write.',
  'The petrol is expensive. I try to be fair, but the prices go up.',
  'I take a few passengers at once. It is a shared ride. The more the merrier.',
  'Please do not lean out of the auto. It is not a bus.',
  'Do not worry about the traffic. I have driven through worse.',
  'My auto has seen many students. They come, they go, they become professors, and they still bargain.',
  'It was the monsoon and I got stuck near the river. A student helped me push. A good boy.',
  'The guards at the gate know me. I wave, they wave. It is a ritual.',
  'I do not allow smoking in my auto. It is my rule, and the passengers like it.',
  'The best fare of my life was a family from Kolkata. They gave me a big tip and a box of sweets.',
  'I am very proud of this campus. I tell everyone that I drive in a famous place.',
  'The students have good manners. They say thank you, and sometimes sorry.',
  'You can call me. My number is on the side of the auto. I answer at any time.',
  'I like it when children wave from the road. I wave back and honk twice.',
  'It is a good life. A steady job, a small house, and a family that waits for me.',
  'Safe journey. Look for the green auto.',
  'Come, I will take you. Where to?',
];

export const family = [
  'Evening tea on the porch, the best part of the day.',
  'Our daughter studies at the Kendriya Vidyalaya here.',
  'Our son plays cricket in the evening. He comes back with muddy knees and a big smile.',
  'We live in the quarters near the road. It is quiet, and the neighbours are friendly.',
  'My husband teaches at the institute. He is usually in the lab, even when he says he is at home.',
  'My wife works in the library. She knows every book, and every student who returns it late.',
  'The children play in the park in the evening. I watch from the porch.',
  'The campus is a safe place to bring up children. They can walk to school without a worry.',
  'We have a small garden behind the house. The tomatoes are red this year.',
  'The monsoon is lovely. The garden is green, and the children are in the puddles.',
  'We grow some flowers at the door. The students stop and take photographs.',
  'We have a dog. His name is Tommy. He thinks he owns the lane.',
  'Our cat visits the neighbours. She has three houses and a lot of food.',
  'The school is five minutes away. The children walk in a group.',
  'We meet the neighbours at the park in the evening. It is our small community.',
  'On Sundays we go for a walk by the lake. The children feed the ducks.',
  'We go to the market on Saturdays. It is a good routine.',
  'The festivals are lovely. We decorate the house, and everyone comes by.',
  'At Bihu we have a small feast. The neighbours bring pitha and laru.',
  'At Diwali the whole colony is lit up. It looks like a small town of lamps.',
  'On Durga Puja we go to the pandal near the market. The children love the lights.',
  'On Eid we exchange sweets. The sevai is the best in the colony.',
  'At Christmas we put a star on the door. The children sing the carols.',
  'We have a small library at home. The children read before bed.',
  'The campus has a good hospital. We are lucky to have it nearby.',
  'We go to the temple in the city once a month. The campus has a small one too.',
  'The roads are quiet. The only traffic is the cycles and the bell.',
  'The guard at the colony gate knows everyone. He gives the children a toffee on Fridays.',
  'The students visit sometimes. My husband invites them for tea. They are shy at first.',
  'I like it when the students come. They remind me of my own children.',
  'My father lives with us. He walks to the lake every morning. He knows the ducks by name.',
  'My mother makes the best tenga. She learned it from her grandmother.',
  'The campus is green. The children know all the trees by name.',
  'In the summer we sit outside in the evening. The breeze from the lake is a gift.',
  'In the winter we keep the fire. The fog is thick, and the evenings are early.',
  'The power goes off sometimes. We light a candle and tell stories.',
  'My neighbour is from Kerala. She taught me to make the best appam.',
  'My neighbour on the other side is from Punjab. We exchange lassi and chai.',
  'There are families here from all over India. It is a small India, a peaceful one.',
  'We learn from each other. The children speak three languages by the age of ten.',
  'The children cycle to school. Their bags are bigger than they are.',
  'The school bus is yellow. It goes round the colony every morning.',
  'We have an annual day at the school. The children dance and the parents clap.',
  'The school has a good garden. My son planted a tomato. It grew bigger than him.',
  'I like the evening walk. The road is lit, and the air is fresh.',
  'The campus has a lovely sunset. The sky turns orange over the hills.',
  'We take the children to the swimming pool in the summer. They love it.',
  'The cricket ground is where the whole family goes for the matches. We cheer for our hostel.',
  'We went to the Pronite last year. The music was loud, but the lights were beautiful.',
  'We watch the convocation from the back. We are proud of all the graduates.',
  'We have a small shop near the colony. It has everything we need.',
  'We buy the vegetables from the market. The vendor knows our order.',
  'We have a gas cylinder delivered every month. The boy is always on time.',
  'The water supply is regular. The tanks on the roof hold enough for the day.',
  'The internet is good. The children do their homework online.',
  'The quarters are old, but comfortable. We have made them our home.',
  'I like the high ceiling. It keeps the house cool in the summer.',
  'The porch is the heart of the house. We sit there with the newspaper and a cup of tea.',
  'The neighbours talk over the fence. The news travels fast.',
  'My daughter wants to study at the institute one day. We tell her to work hard.',
  'My son wants to be a cricketer. We tell him to study first.',
  'The grandparents visit in the holidays. They bring a lot of sweets.',
  'The grandchildren ride the cycle with a small seat. They love it.',
  'My day: wake up, make tea, send the children to school, do the chores, wait for them.',
  'I volunteer at the school library. It is a joy to read to the little ones.',
  'I teach a class at the community centre. The women of the colony learn to stitch and to read.',
  'We have a ladies\' club. We meet every Wednesday, and we talk about everything.',
  'The men play cards on Sundays. The women do not mind, as long as the tea is made.',
  'We have a cultural evening once a year. Dance, songs and a play.',
  'Our colony has a small temple. The priest comes on Thursdays.',
  'The colony guard goes around at night with a stick and a torch. We sleep well.',
  'The jackals howl at night. The children are afraid, and then they laugh.',
  'We see the monkeys sometimes. They take the clothes from the line.',
  'We have a bird feeder. The mynas and the sparrows come every morning.',
  'The lake birds are visible from the road. A flock of egrets comes at dusk.',
  'We saw the fireflies last evening. The children counted them.',
  'The monsoon brings frogs, and then the cranes. I think the cranes are the elegant ones.',
  'The campus is a quiet place to grow old. We have friends, a garden, and a lake.',
  'The best thing about living here is the neighbours.',
  'There is always something to do. A talk, a play, a match, a market.',
  'Come, sit, have some tea. You look like you have been walking all day.',
  'Do not leave without a biscuit. It is a rule in this house.',
  'You are always welcome. This is a friendly colony.',
  'Come again. Bring the children. The garden is better in the evening.',
];

export const scholar = [
  'Fifth year of my PhD. Almost there.',
  'The married scholars hostel is a small village of its own.',
  'My thesis is on a topic that I explain in one sentence and defend in two hundred pages.',
  'My supervisor is very kind. And very busy. Both are true.',
  'I work in the lab from nine to nine. Sometimes the lab works me.',
  'The experiment failed again. It is the seventh time. The seventh time is the charm, I hope.',
  'I submitted a paper last month. The reviewers have been quiet since.',
  'Reviewers\' comments are the best teachers. Also the most painful.',
  'The conference is next month. I need to finish the slides, the figures and the courage.',
  'I teach a tutorial for the first-year students. They ask better questions than my committee.',
  'I live with my wife and a small child in the married scholars hostel. The campus is a good place for a child.',
  'The hostel has a small playground. The children play together, and the parents drink tea.',
  'We cook at home. The mess is for the single students. We miss it, a little.',
  'The stipend is small, and we make it work. It is a skill in itself.',
  'I cycle to the lab every morning. The green lane on the new road is my favourite part.',
  'I like the lake in the evening. A quiet walk helps the mind.',
  'I do my best thinking on the way to the library, and my best writing at two in the night.',
  'The library is open until two. It is a scholar\'s second home.',
  'The tea stall near the lake is our meeting point. Many research ideas were born there.',
  'I met my best friend here. He is also a scholar. We complain together.',
  'It is lonely at times. Every scholar has a lonely stretch. It helps to have people.',
  'Do not skip meals. I know the lab is calling. The body is calling louder.',
  'I take a walk every day. Even ten minutes. It keeps me sane.',
  'My field is hard. My notebooks are full. My coffee mug is empty.',
  'We are building a collaboration with a lab abroad. The visa is the hardest part.',
  'The institute has good equipment. We just need a good idea to use it.',
  'My research is on something you would find in the news in ten years. Maybe.',
  'I read about fifty papers a month. I understand about ten.',
  'The best paper I read was written by a student. A small paper with a big idea.',
  'I mentor a few undergraduates. They are so enthusiastic, I feel old.',
  'The first year of the PhD is about reading. The second about failing. The third about trying again.',
  'I want to be a professor. Or a researcher at a good company. Or a farmer.',
  'My parents are proud. They tell their friends that I am a doctor. I explain I am not that kind.',
  'The thesis is a long road. I am on the last mile. The last mile is the longest.',
  'There is a quiet room in our hostel for writing. The only rule is silence.',
  'It is a good community. The scholars help each other, with code, with data, with chai.',
  'The hostel dinner is a social event. We discuss work for five minutes and everything else for an hour.',
  'We organise a cricket match every month, the scholars against the faculty. The faculty wins, thanks to the umpire.',
  'The scholars\' festival is my favourite. We cook, we sing, we forget the deadlines.',
  'I take my daughter to the park near the lake. She feeds the ducks and I feed my thoughts.',
  'My wife is also a scholar. We have a deal: one of us is allowed to be stressed at a time.',
  'We share the lab computer. The queue starts at midnight.',
  'The server is down again. I am used to it. The server and I have a relationship.',
  'The cold room in the lab is my favourite place in summer.',
  'I presented at a seminar yesterday. The audience asked three questions. I answered one.',
  'The best audience is the one that asks the hard questions. The best question is the one you cannot answer.',
  'My advisor says: write a little every day. I do. One line.',
  'I believe in a good break. A walk to the View Point trail is a perfect one. Long, quiet, and green.',
  'I walked the View Point trail last week. Two and a half kilometres up. The forest was dense and silent. I solved a problem on the way.',
  'I like the early morning. The campus is quiet, and the lab is mine.',
  'When the experiment works, it is the best feeling in the world. It happens twice a year.',
  'The institute has a good counselling service. I used it once. It helped more than I thought.',
  'If you need help with your project, ask a scholar. We have more time than you think. A little.',
  'The graduate students\' council meets on Fridays. We talk about the stipend, the hostel and the tea.',
  'I like the monsoon in the lab. The rain on the window, the warm tea, the soft hum of the machine.',
  'We had a small celebration when the paper got accepted. A cake, a card, and a very tired scholar.',
  'The Technology Park is near. We hope to collaborate with the start-ups there. Maybe a spin-off.',
  'I have an idea for a start-up. I will test it when I finish the thesis. Maybe.',
  'My research has a small practical use. It is in the farm sensors. A little thing that helps.',
  'The campus is a good place to do research. The distractions are few and green.',
  'Always back up your data. Twice. In two places. And in your head.',
  'Writing the thesis takes more time than doing the research. Nobody tells you that.',
  'I like the library\'s old journals. I find ideas that nobody uses now, and some are gold.',
  'My department is friendly. We have a small kitchen with a kettle and a plate of biscuits.',
  'My office is a desk in a shared room. I have a plant on it. The plant is doing better than me.',
  'I started the PhD with a plan. The plan changed in the first month. It is still changing.',
  'The funding is secure for two more years. I am grateful for that.',
  'The scholars\' hostel has good Wi-Fi. It is the one luxury we have.',
  'Our supervisor invited us home for dinner. The food was great, and the conversation was even better.',
  'On Sundays I go to the market and buy vegetables for the week.',
  'I miss my hometown sometimes. The campus has a way of making me feel at home.',
  'The students call me bhaiya. I feel like a part of the family.',
  'I have seen four batches of students come and go. They grow up fast, and so do the trees.',
  'The best advice I got was: finish the thesis. The second best was: have a hobby.',
  'My hobby is gardening. I have a few plants on the balcony. They need no thesis.',
  'The mornings here are beautiful. A mist over the lake, birds on the road, and a hot cup of tea.',
  'Do come to my talk. It is on Thursday. Free snacks, and I will try not to bore you.',
  'I will be done soon. And then I do not know what I will do. Maybe a holiday.',
  'There is a good future in research. It is a slow road, but a rewarding one.',
  'Thank you for listening. Most people ask how long it will take. You asked what I do.',
];
