// What people say when you talk to them (E): guards, students, faculty, heads of department, deans and the director.
// Every role has its own lines; dialogue.js mixes in lines that depend on the time, the weather, the events and where you are.
// Names of real people and of companies are left out on purpose.

export const guard = [
  'Namaste! Everything alright? Do you need directions?',
  'Please carry your ID card. The guards check it at the gate and at the hostel doors.',
  'The Main Gate never closes. The KV Gate and the Khokha Gate shut at 10 at night and open at 6 in the morning.',
  'The scan desk is right here: scan your QR to make your entry, in or out. It only records the time, the gate is just a gate.',
  'Going to the market? Take the Khokha Gate: it is the short way, five minutes on foot.',
  'Visitors must sign the register at the hostel door. Even your own cousin. Rules are rules.',
  'Boys cannot go up to the girls\' hostels, and the other way round: the common room downstairs is for guests.',
  'Cycles are not allowed up the View Point trail. It is only for people on foot, and it is a long climb.',
  'The View Point is a long walk, two and a half kilometres uphill. Carry water and start before it gets dark.',
  'At night keep to the lit roads. The jackals come down from the hill after dark, they will not bother you but do not follow them.',
  'Dogs on campus are friendly mostly. Do not tease them and they will not tease you.',
  'Lost something? Tell the guard at the nearest gate or hostel desk; things come back to us all the time.',
  'Ambulance? It goes out through the Main Gate, always keep the road clear for it.',
  'Speed limit is thirty on campus. The cycles forget it going downhill, so mind the slopes.',
  'Helmets for scooters, please. A cracked head is a long hospital stay.',
  'Parking only at the cycle sheds. The solar roofs keep the sun and the rain off your cycle.',
  'Outsiders without a pass cannot come in after dark. Visitors have to be called in by someone inside.',
  'Delivery riders wait at the gate. They cannot go up to the hostel rooms, the student comes down.',
  'I have been on this shift since six. The tea from the stall is what keeps me awake.',
  'Three shifts here: six to two, two to ten, ten to six. The night one is the quiet one.',
  'Fire exits stay clear. Do not park your cycle in front of them, ever.',
  'If you see anything odd, tell us. A phone left on a bench is not odd, a ladder against a wall at midnight is.',
  'Alcheringa week: the gates are very busy and we check the passes of every outsider. Show yours.',
  'Techniche week brings thousands of visitors. We put extra guards at every gate.',
  'The Main Gate has the sandstone name stones in three languages: English, Assamese and Hindi. Take a photo, everyone does.',
  'The KV Gate has a post office built into its wall. Letters, parcels, stamps, all there.',
  'That cement guard post at the KV Gate was 3D printed, layer by layer. It was a trial for printed buildings.',
  'Sit down for a minute if you are tired. There is water in the cooler by the desk.',
  'Rain? The gate cabin leaks in one corner, so I move the chair. Every monsoon the same.',
  'Do not cross the roads between the zebra stripes and the kerb. The campus roads look quiet, but the buses do not stop quickly.',
  'The cycle lane is the green strip on the outer side of the two-lane roads. Stay in it, the cars keep to the middle.',
  'Please do not climb the boundary wall. The barbed wire is old and it is a long way to the hospital.',
  'The lake is for looking at and for boats. Swimming in it is not allowed, whatever your friends say.',
  'Boats are on the IITG lake only, from the jetty. Life jackets are on, no standing up in the boat.',
  'The pool is for students and families with a card. Ask at its gate.',
  'No cricket on the roads, please. The cricket ground is for cricket.',
  'This campus is more than seven hundred acres, and I have walked most of it on rounds.',
  'We count the cycles in the sheds at night. Do not leave your lock open and a note will find you.',
  'Mind the rhino statue at the circle, it does not move out of the way of cycles.',
  'There are monkeys near the hill. Keep bags closed, they know what a lunch box is.',
  'Hostel doors close at night for the visitors, not for you. Scan your card and go in.',
  'Some students sneak out through the Khokha Gate after ten. The guard there knows each one by name.',
  'Come after the exams, it is much calmer. During the exams the library gate guard drinks six teas.',
  'Convocation day is the proudest day for the guards also. We stand in our best uniform at the gate.',
  'Fresher\'s week: parents everywhere, bags everywhere. We help carry the heavy ones up the steps.',
  'Everyone lost on the first day asks me: where is the Academic Complex. It is the big one with the Cores.',
  'To the Administrative Building, walk past the library towards the flag lawn. The director\'s office is inside.',
  'The hospital is open all day for OPD and the emergency never closes. Walk straight down the main road.',
  'The Guest House is by the lake, near the north side. Parents like it more than the hostels.',
  'The nearest ATM is in the Market Complex. It is out of cash on the first of every month.',
  'This is the gate pass register. Everyone who goes out writes the time and where. Everyone who comes in writes the time.',
  'If you are going out after dark, write where you are going. If anything happens, we know where to look.',
  'My family stays in the quarters near the KV. My daughter studies in the school here.',
  'I am from a village near Barpeta. Twelve years here now. It feels like my own place.',
  'Good morning! The air is the best at six, before the buses start.',
  'The gate light comes on by itself at dusk. If it does not, tell me, I call the electrician.',
  'The cleaning staff start at six. If you see the road being swept, walk on the other side.',
  'Do not feed the dogs next to the gate. They follow you for weeks and then I have to chase them away.',
  'Press the bell on the bus if you want to get off. It stops only at the shelters.',
  'The campus bus starts at the IITG Bus Stop. First bus seven in the morning, last at ten at night.',
  'There is a guard at every circle too, waving the traffic. It is the most boring and the most important job.',
  'At the lake circle there is the air quality board. Today it looks fine, but the board is honest about the winters.',
  'Take care of the plants. The gardeners work hard and a footprint on a new lawn ruins a week.',
  'Please keep to the paths in the forest trail. The ground can slide after the rain.',
  'I cannot let that in without a pass. Sorry, I know you are a friend of someone.',
  'Do you have a gate pass for the guest? Ask at the Main Gate, the hostel will confirm the name.',
  'Girls\' hostel guards are more strict, and I am glad. A safe campus is a quiet one.',
  'The ID card is also your library card and your mess card. Do not lose it.',
  'If you lose your ID card, the hostel office makes a new one after a form and a small fee.',
  'Students from the first year are the most lost, and the most polite. The final years nod and walk on.',
  'Sports day: the track gets crowded, the gates stay open longer. I like the evening races.',
  'Mind the speed breakers. Oh, there are none on these roads, so mind the cyclists instead.',
  'We have thirty guards on the main roster and more for events. We are not just for the gates.',
  'The new fence at the lake is for your safety. The boats are the only way in.',
  'Torches are in the locker. At night I walk the lake road and the hostel side with one.',
  'The Khokha side market is open late. The guard there closes the gate at ten sharp and does not argue.',
  'I have seen four Directors in my time here. The campus changes, the gate stays the same.',
  'You look lost. Tell me where you want to go and I will point the shortest way, not the prettiest.',
  'Did you try the tea at the stall by the lake? It is the best on this side of the campus.',
  'There is a first aid box in the cabin if you scrape a knee on that cycle.',
  'Take a photo in front of the name stones, and not on the road, please.',
  'Everybody asks if I get bored. Not really, I watch the people. Every day a story.',
  'Sundays are slow. Mostly families and cyclists. I read the newspaper twice.',
  'If you see someone without an ID card inside a hostel, tell the hostel guard, not the other students.',
  'The monsoon floods the road near the Khokha side. The water goes down in an hour.',
  'Drones are not allowed over the gate. If you fly one, tell the Security Office first.',
  'The roundabouts have a rule: the one already on the circle goes first. Cycles too.',
  'Please switch off the loud music near the hospital and the library. Both are quiet zones.',
  'Come here in January when the fog sits on the lake. It is beautiful, and very cold at six.',
  'We have a small cricket match among the guards on Sundays. I bowl, the others cheat.',
  'Thank you for asking, most people just walk past. Have a good day.',
];

export const student = [
  'Which hostel are you in? Come over for dinner at ours tonight!',
  'The mess food is actually good today. Not every day, but today.',
  'Alcheringa passes are out. Get yours before they run out, last year it took three hours.',
  'Did you finish the assignment? The deadline is Friday midnight and the portal always hangs at 11:58.',
  'Tapri after class? Chai and a samosa, five minutes. I will pay if you carry my bag.',
  'The library is open until two in the night. I am there more than I am in my room.',
  'Cycles are a lifeline here. Do not leave yours unlocked, it will be borrowed and returned in a different colour.',
  'First year is all about the Cores. Three buildings to find, and each has a different staircase.',
  'The best momos are at the market, not at the food court. Do not tell the food court.',
  'I came for the CSE, I stayed for the sunsets on the lake.',
  'Midnight canteen noodles are a sacred tradition. The hostel canteen opens at six in the evening and shuts at two.',
  'Do you play something? Every hostel has a cricket team and a guitar.',
  'The lake at dusk is the best place to think. Or to avoid thinking.',
  'There is a trail to the View Point, two and a half kilometres, up through the forest. Go early, take water.',
  'Attendance is not compulsory in some courses, and in others the professor knows your face.',
  'The professors here actually reply to emails. Not at midnight, but they reply.',
  'Exams week: the library fills up by eight and the extra reading room opens.',
  'Pronite is my favourite night of Alcheringa. A tired singer, a loud crowd and a floodlit ground.',
  'Techniche is for the nerds, Alcheringa is for everyone, and Spirit is for the athletes.',
  'I was in the Dance Club in my first year. Now I only dance in the corridor.',
  'The OneStop app is where I scan for the gate and check the mess menu. Do you have it set up?',
  'Guests can eat in our mess with a coupon. Fifty for breakfast, seventy-five for lunch and dinner.',
  'Sunday dinner is the special thali. Ninety rupees and worth it.',
  'Do not skip breakfast, the mess runs out of everything by nine.',
  'The cycle stands with the solar roofs are the nicest thing about our hostel. Shade, and a place to leave the cycle.',
  'My roommate is from Kerala and I am from Delhi. We argue about rice, and agree about biryani.',
  'Every hostel is named after a river of the North East. Mine is Manas, a river and a wildlife park.',
  'The cricket ground has a proper stage now. The Pronite acts play there.',
  'Have you seen the graffiti on the hostel walls? Each has the hostel name and a slogan.',
  'Library cards also work as the mess cards. Do not lose it, the fine for a new one is more than a dinner.',
  'We have an inter-hostel quiz on Wednesday. Join our team, we need a general knowledge person.',
  'The Technology Park is the new building cluster on the old east cricket ground. It is where the start-ups will sit.',
  'The IITG Bus Stop is where all the campus buses start. I take the one to the Academic Complex at eight.',
  'Placement season makes everyone quiet. Do not ask me about my package.',
  'I am doing a project on traffic flow. The campus roads are my lab.',
  'The best sleep is during the afternoon lecture. The second best is during the evening one.',
  'Go to the Gym in the morning. The evenings are packed and the treadmills are all taken.',
  'The swimming pool is open from six to nine in the morning and four to eight in the evening.',
  'My phone dies every day by four. I charge it in the library, near the plug by the window.',
  'Wi-Fi is better in the lecture halls than in the hostels. We carry laptops to the corridors.',
  'There are two kinds of students here: those who sleep before ten and those who start working at ten.',
  'Have you tried the lemon tea at the library stall? It is the only thing that works at 1 AM.',
  'The first year is mostly about learning how to wash your own clothes.',
  'Hostel mess committee meetings are like parliament, with a smaller budget.',
  'I take the cycle lane on the two-lane roads. The cars in the middle, the cycles on the green strip.',
  'The campus is huge. I ride five kilometres on a normal day, and I never leave the gate.',
  'Joined the photography club. There is a sunrise at the lake that does not look real.',
  'Whenever it rains the whole campus smells of wet soil. I love it, my laundry does not.',
  'There are stray cats near our hostel who know my schedule better than my professor.',
  'I borrowed a cycle from the stand and the owner is still looking for it. Not me, I returned it.',
  'We went boating on the lake. Rowing is harder than it looks, and the speedboat is a cheat.',
  'Do you know about the rhino statue at the circle? Mother and calf. Everyone takes a photo.',
  'Aaj mess mein kya hai? I check the board at the door every time, even though I know.',
  'The hostel day starts at noon and ends at four. In that order.',
  'I like the fog in January. You can hear the bicycle bells before you see anyone.',
  'Competitive coding contest on Saturday in the LHC. Free pizza for the winners.',
  'Everyone should watch one sunrise from the View Point. Everyone should also take the bus back.',
  'The Brahmaputra is just outside the campus. In the evening we go to the bank on cycles.',
  'The dogs on campus are better fed than most students. The biscuit sellers are not complaining.',
  'My seniors told me: take the extra course, not the extra mess coupon. They were right on one.',
  'The library has a silent floor and a not-so-silent floor. I study on the second kind with music.',
  'If the lift in the Academic Complex works, buy a lottery ticket. It is a lucky day.',
  'The Lecture Hall Complex has the biggest classrooms. Two hundred students and one fan.',
  'My dream is to start my own company. The Technology Incubation Centre has a desk for that.',
  'My parents think I study all day. I let them.',
  'I have a lab at eight on Monday, which is a human rights violation.',
  'The best view of the campus is from the top of the hill, and the best view of the hill is from the lake.',
  'We went to Kaziranga last month with the club. A rhino crossed in front of the jeep. Real, not the statue.',
  'The campus has more trees than students. Count them if you do not believe me.',
  'The guard at our gate is called Dada. He knows everyone\'s name and everyone\'s secret.',
  'Never lend your cycle. It will come back with someone else\'s name stuck on it.',
  'The Sunday special thali is the reason I come to the mess on Sundays.',
  'If you want peace, the guest house lake is quieter than the main lake.',
  'Night walks on campus are safe, and the stars over the lake are something else.',
  'You can always find me at the tea stall by the lake after lecture. Join me.',
  'My brother is in the second year of mechanical. We argue whose department is harder. Both are.',
  'We have a Hindi poetry club, a Bihu club and a heavy metal club, and all of them practise in the same building.',
  'There is nothing like cold coffee at midnight in the hostel canteen, after an exam.',
  'The cycle tour of the campus takes about an hour. Book it from the planner if you are new.',
  'The best seat in the mess is next to the fan. Come early.',
  'The Cores are named by number. Core 5 is at the west edge, and that is where the cycles go to rest.',
  'After lunch the whole campus slows down. The dogs take the shade first, then the students.',
  'The boats on the lake cost twenty rupees for a rowing boat and sixty for the speedboat. Cheap for the memories.',
  'Alumni come back for the convocation and cry at the lake. It is not the lake, it is the memories.',
  'I proposed to my friend in front of the rhino statue. She said I had to ask in the lab. We are still friends.',
  'My best friends are the ones I met in the mess queue.',
  'Be careful with the slope near the lake in the monsoon. The mud is slippery, and the mud wins.',
  'You can call the hostel guard if you lose the key. He has a copy of everything and judges you silently.',
  'The two-lane roads are new. The green strip is for cycles, and the flower beds in the middle are the pride of the gardeners.',
  'There is a trick: the Khokha side market is cheaper than the campus one, by about ten rupees.',
  'I am learning Assamese. Nomoskar is hello, and everyone smiles when you try.',
  'Whenever someone asks me what IITG is like, I say: green, wet and friendly.',
  'The hospital is good for fever and bad for excuses.',
];

export const faculty = [
  'Good to see you. Do not forget the quiz on Monday.',
  'My office hours are four to five in the afternoon. Drop by with questions, not only with complaints.',
  'Research is mostly patience, and a good cup of coffee.',
  'Have you read the paper I shared? Section three is the interesting part.',
  'You can always email me. I reply by the weekend, usually.',
  'Attendance helps more than notes. Come to the lectures.',
  'The best projects start from a small question you cannot stop thinking about.',
  'The Cores are not a maze, they are a grid. You will see it when you are in the third year.',
  'The campus is the best part of working here. A lake outside the window is not a bad thing for an office.',
  'First years often ask when they can do research. Now. Ask a professor you like.',
  'The Technology Incubation Centre helps with start-ups. If you have an idea, go and talk to them.',
  'The library has all the journals you need. And a quiet corner for the ones you do not.',
  'We are building the Technology Park on the old east cricket ground. A good use of the grass.',
  'The campus has one cricket ground now, and the Pronite stage stands at its edge.',
  'In the monsoon the lab roof leaks. Research continues, with buckets.',
  'Please do not copy assignments. I can tell, and so can the plagiarism software.',
  'The best question in my class this year was from a student who had not read the chapter.',
  'I started here when there were fewer buildings. The trees were smaller, the lake was the same.',
  'I cycle to work. The two-lane roads have the green lane now, and I feel like a king.',
  'The students\' energy is what keeps us young. Their noise is what keeps us tired.',
  'There is a seminar every Thursday at four. Free, with snacks, and sometimes with ideas.',
  'Grading tests on a Sunday while watching the lake is the best part of this job. Almost.',
  'The Convocation is my favourite day. Everyone is nervous, and so proud.',
  'The campus has more birds than people in the morning. Walk by the lake at six and count the species.',
  'Be curious. A good degree is a by-product, not the goal.',
  'The lab is open until half past five. Finish your readings and clean the bench.',
  'You asked about the research internship. Send me your CV and a paragraph about why.',
  'Summer interns are welcome. Two months, a real problem, and no guaranteed result.',
  'Do come to my class, even if you do not take the course. I do not mind the extra noise.',
  'I remember your face from the lecture. Third row, left corner, reading the other textbook.',
  'The best time to meet me is just after the morning class, when I am still in a good mood.',
  'The deadline is the deadline. A good reason helps, a good excuse does not.',
  'You can borrow my notes. Not for the exam, for the understanding.',
  'If you are interested in AI, the conference centre has a talk in the AI Confluence week.',
  'The Academic Complex was built to keep the departments close. It also keeps the gossip close.',
  'Please do not prop the lab door with a chair. We have safety rules for a reason.',
  'The Alcheringa band was louder than my lecture. I forgive them.',
  'Techniche brings the best of the engineers. I sit in the audience and feel old and proud.',
  'The hostel wardens are heroes, but do not tell them, they will ask for a raise.',
  'If you have a problem, come to me before it becomes a crisis.',
  'My research is on something you have not heard of. Neither have most of my colleagues.',
  'Take the cycle for the long distances. The Academic Complex to the hostels is a short ride with a long walk back.',
  'You should try the View Point at least once. Take the trail, not the shortcut. There is no shortcut.',
  'I met my spouse here, at a lab meeting. It is the most efficient meeting I ever attended.',
  'The campus has a school, a hospital and a post office. You can live here and not leave for a month.',
  'Your question was good. I do not know the answer, which is the best kind of question.',
  'I walk along the lake after lunch. It is the one meeting nobody can schedule over.',
  'Let me know when you are ready for a different kind of problem. I have a list.',
  'The laboratory is not a classroom. It is a place where things go wrong in an organised way.',
  'Stay curious, stay humble, and back up your data.',
  'I tell my students: the first draft is for you, the second draft is for the reader.',
  'Learn to write. A clear paragraph beats a clever formula.',
  'Do not underestimate the library. The best things are not on the internet.',
  'If your lab report is late, tell me before the deadline, not after.',
  'The best discussions happen at the tea stall, not in the classroom.',
  'I started my career writing a thousand lines of code a day. Now I write ten, and think about them for a week.',
  'This semester I am teaching a course on design. Come, it is full of arguments.',
  'You do not need to be the first in the class. You need to be the one who asks why.',
  'The monsoon brings a smell I have missed in every other city.',
  'It is nice to see someone talking to the faculty without a reason. Thank you.',
  'The staff here are the reason everything works. Say thank you to them also.',
  'Keep your notebooks. In ten years you will read them with a smile.',
  'The visiting scholars say the campus is the greenest in India. I have no reason to argue.',
  'A tip for exams: sleep well. Nobody ever remembered the one formula they stayed up for.',
  'You will see me at the lake in the evenings with a book. Say hello, I do not bite.',
  'The best projects I have seen were done by students who did not know what was impossible.',
  'The Technology Park will have industry labs. Good for placements, better for ideas.',
  'In my department there are more start-up ideas than chairs. Come and join us.',
  'I am happy to guide a final-year project. Come with a topic and a reason.',
  'Please keep the classrooms clean. The cleaning staff do not deserve the chai cups.',
  'Take notes by hand. It helps you think, and the laptop will not run out of battery.',
  'If your experiment fails, write down why. It is the most valuable page in the notebook.',
  'I like the early morning labs. The campus is quiet, and the instruments are less moody.',
  'My students ask when I sleep. During their presentations, I joke.',
  'If you want a recommendation letter, ask early, and bring a list of what you did.',
  'I judge a student by the questions, not the answers. The answers can be copied.',
  'The Director\'s office is in the Administrative Building. The doors are open more than you think.',
  'I sit in the Faculty Club on Fridays. We argue politely about everything, except the budget.',
  'The best compliment I get is when a student says: I went back and tried it myself.',
  'It is easy to be busy and hard to be useful. Choose carefully.',
  'The campus gets very quiet in the vacations. I walk the empty roads with a smile.',
  'The boats on the lake are for fun. Do not fall in, I have to write the incident report.',
  'Remember to eat. The mess closes at nine forty-five and I have seen the whole lab starve.',
  'The two-lane roads have flowers in the middle now. Even the traffic is more cheerful.',
  'If someone tells you it is easy, check again. If someone tells you it is impossible, check once more.',
  'Many students here are the first in their family to study engineering. That is a weight, and a gift.',
  'Questions after the class, please. Even the ones you think are silly. Especially those.',
  'If you see a student who looks lost, say hello. It costs nothing and it is remembered.',
];

export const hod = [
  'Our department seminar is on Thursday at four. You should attend.',
  'Projects are open for summer interns. Send me your CV and a short note on what you want to learn.',
  'Hard work and curiosity: that is all it takes. Talent is the smaller part.',
  'The department has a new lab opening this semester. Come and see before the crowd.',
  'We are choosing the best final-year projects for the exhibition. Start early.',
  'The first-year students ask what the department does. Everything, sometimes at the same time.',
  'Our faculty meetings are long. The agenda is short, the opinions are not.',
  'We have a wall of student projects near the entrance. Every year something on it surprises me.',
  'Collaboration is the way forward. We work with other departments on almost every grant.',
  'Funding is always the problem. And always the solution, if you write a good proposal.',
  'The department tea is at four. The best ideas have been spoken over it, and the worst ones too.',
  'Our alumni are everywhere. They send emails from airports and labs.',
  'We have an open day soon. Visitors come from the school, and they ask the best questions.',
  'Research scholars are the engine of the department. Be kind to them, they work long hours.',
  'The lab safety rules are not suggestions. Goggles on.',
  'Come and see the new equipment. It took two years to arrive and thirty seconds to break. We fixed it.',
  'Curriculum changes take a year of meetings. The students notice in a day.',
  'Placements are important, and so is learning something that lasts.',
  'Attend the conferences, even the small ones. People remember who asked a good question.',
  'We are hiring new faculty. Tell your seniors who are thinking about a PhD.',
  'The department office handles the forms. Be polite to them, they know everything.',
  'The department library has old theses. Read one. It is a lesson in perseverance.',
  'Industry projects are good for the students. The deadlines are different from the exams.',
  'The AI Confluence is in the Conference Centre this week. Many of our scholars are presenting.',
  'In the monsoon the corridor leaks near the staircase. We call it the waterfall seminar room.',
  'Let me tell you about the lab tour. It starts at the second floor and ends at the tea machine.',
  'Our students did well at Techniche. The robotics team stayed up three nights in a row.',
  'We keep a quiet room for the scholars. The only rule is: no discussion about deadlines.',
  'The department tries to keep the first-year labs fun. A broken bulb is also a lesson.',
  'Departments here are friendly rivals. We compete at cricket and cooperate everywhere else.',
  'Do not be shy to ask a senior. They were in your place not so long ago.',
  'The Cores are the heart of the campus. You will walk their corridors more than you walk your own room.',
  'We are proud of our labs. The air conditioner in one of them is older than the department.',
  'Come and sit in our reading room. It is the quietest in the Academic Complex.',
  'The research scholars need volunteers for a small study. A free coffee is included.',
  'Exam duty is the worst part of my week. The best part is seeing a student smile after the paper.',
  'I like walking to the Administrative Building. The flag lawn is always in good shape.',
  'The monsoon term is the busiest. The rain keeps everyone indoors and productive.',
  'Do read the notice board on the first floor. The best talks are announced there.',
  'The department has a cycle stand with a solar roof now. The students are very pleased, and so is the sun.',
  'We organise an annual workshop for school teachers. It is my favourite week.',
  'Our budget is small, our ambitions are not.',
  'I try to remember every student\'s name. I fail after the first hundred.',
  'The best advice I got: work on a problem you would still enjoy if nobody read your paper.',
  'In this department the doors are open. Knock anyway, it is polite.',
  'Mentoring is a two-way street. I learn more from the students than they think.',
  'We are building a collaboration with the Technology Park. More labs, more ideas.',
  'The scholars at the lake in the evening are not wasting time. Half of the good ideas come from walking.',
  'Take your time with the thesis. A good one needs two more years than you plan.',
  'We have a visitor from abroad next week. Please be on time, and be yourselves.',
  'Our department photo is on the wall near the stairs. The one from the first year is the funniest.',
  'The weekly meeting starts at ten. Coffee is at ten past.',
  'It is important to say thank you to the technicians. The experiments work because of them.',
  'The best seminar this year was on a topic I did not understand. Everyone was excited.',
  'When the power goes off, we have a generator. When the generator fails, we have patience.',
  'The faculty room has a kettle and a window to the lake. There are worse offices.',
  'I took the bus to the Technology Park yesterday. A short ride, a long meeting.',
  'We hire our own students sometimes, after they have been away for a few years. It is the best kind of return.',
  'Keep the lab tidy. Tomorrow\'s experiment will thank you.',
  'A degree is a licence to learn. Do not stop.',
  'The students\' feedback forms are useful, and sometimes hilarious.',
  'The department mailing list is for announcements, not for jokes. The jokes go to the other list.',
  'Remember to cite your sources. The first citation is a courtesy, the last one is a necessity.',
  'I will be at the seminar room if you need me. Bring a question, not a complaint.',
  'The research scholars\' hostel is a village of its own. They organise the best festivals.',
  'Our Head of Department meeting with the Dean is next week. Please do not ask me about the budget.',
  'The Annual Day is a good chance to show your project to the family.',
  'We work with the hospital on some health projects. Sensors and data, not stethoscopes.',
  'Do join a club. The ones who only study come out half-educated.',
  'My favourite part of the day is when the corridor fills with students at ten past the hour.',
  'We have a robot in the lab. It does not complain, which makes it a good colleague.',
  'Our final-year project exhibition is a mini-Techniche. Free entry, free ideas.',
  'There is no shortcut to understanding. There is only practice and good company.',
  'Open the window of the lab sometimes. The campus air is the best coolant we have.',
  'Please do not leave food in the lab. The ants have their own research project.',
  'I walk through the Cores every morning. It is five minutes of silence before the day starts.',
  'If you are stuck, take a walk. The solution is usually waiting at the lake.',
  'We train students to be good engineers. We hope they are also good people.',
  'Our external examiners always say the same thing: your students ask better questions than most.',
  'The department has a small museum of old instruments. Ask for the key at the office.',
  'I wish more students would visit the workshop. Machines are the best teachers.',
  'If you ever need a reference, tell me. If I do not remember you, remind me of a good story.',
  'The seminar hall gets cold in the afternoons. Bring a jacket, and an open mind.',
  'This is a department, not a factory. Take your time, enjoy the work.',
  'The key to a good department is people. The rest is furniture.',
];

export const dean = [
  'Welcome to IIT Guwahati. Make the most of these years.',
  'The Student Senate meets on Wednesday. Bring your ideas, not only your complaints.',
  'Our campus is one of the greenest in India. Keep it that way.',
  'The Dean\'s office is open to students. Make an appointment, or come early and be patient.',
  'I handle the academic matters: courses, grades, the calendar. I am also the person who says no to extensions.',
  'The academic calendar is planned a year ahead. Please check it, do not trust the rumours.',
  'Student affairs are about more than rules. It is about making a place where people can grow.',
  'Hostel life is a part of the education. The mess committee teaches more about management than a textbook.',
  'We are building facilities for research, for sports and for the clubs. A campus is more than classrooms.',
  'The campus has a new Technology Park. It will connect the students with industry.',
  'Anti-ragging is serious. If anyone troubles you, tell us. No one will blame you.',
  'The counselling centre is there to help. Using it is a sign of strength.',
  'The Research and Development office helps with funding. Ask your professor before you come to us.',
  'The faculty are here to help you learn. They also have their own deadlines, so be patient.',
  'Infrastructure is a long-term game: a building takes years, a leaking roof takes seconds.',
  'The Alumni Affairs office likes to hear from you. In ten years, write back.',
  'The Convocation is the best day of the year. The rain also comes, as a guest.',
  'The campus is a village of ten thousand people. We try to make it work for all of them.',
  'The Senate has student representatives. They speak, we listen.',
  'We try to keep the campus accessible: ramps, lifts, a good path.',
  'The scholarship forms are due soon. Please do not wait until the last day.',
  'The roads are being improved. The two-lane roads have a green cycle strip, so use it.',
  'The security team and the maintenance staff are part of the institute. Treat them with the same respect as the professors.',
  'The hospital has an ambulance on call all the time. If you see it, give way.',
  'You are the reason the institute exists. Remember that on the bad days.',
  'Every festival brings thousands of visitors. We plan for months. Help us by being good hosts.',
  'The new buildings are designed to blend with the trees. We have never cut a tree without planting two.',
  'Questions about courses? Ask the course coordinator. Questions about the system? Ask me.',
  'The campus rules are for everyone. They apply to the Dean, too.',
  'We are proud of the clubs: music, drama, coding, dance, photography. Each of them is a small school.',
  'The cycle policy: cycles on the roads and cycle lanes, not on the lawns, and not on the View Point trail.',
  'The View Point trail is on foot only. It is the way we like to keep that corner of the campus quiet.',
  'The Dean of Faculty Affairs looks after the teachers. Without them, there is no institute.',
  'It is our duty to make the labs safe. Please follow the rules even when the instructor is away.',
  'We have a new bus stop terminus. All the campus buses start from it.',
  'Our energy plan includes solar roofs. The cycle sheds already have them.',
  'The fees are as low as we can keep them. Education should not be a burden.',
  'The first year is hard for most. You are not alone.',
  'You can approach me at the Administrative Building. The office is beside the flag lawn.',
  'If you have a good idea, write it up. Ideas that are on paper get discussed, those in the head do not.',
  'Keep the campus clean. The green bins are for wet waste and the blue for dry.',
  'Our campus lake is a habitat. Please do not feed the fish, or the ducks, too much.',
  'The guard at the gate is as important as the professor. Be kind to both.',
  'We try to include local culture: Bihu, Assamese music, the gamosa at the convocation.',
  'The Pronite stage is permanent now. It has a lighting truss, and the sound is better than before.',
  'The workshop is open for all students, not only mechanical. Learn to make something.',
  'We are strict about plagiarism, and kind about mistakes. There is a difference.',
  'Do not be afraid of failure. The institute has seen many failed experiments and some are now famous.',
  'The Research Park will bring industry to the campus. Prepare to meet people who will ask what your project is for.',
  'Students from the North East make up a big part of this place, and it is richer for it.',
  'I enjoy walking in the evening. The lake road is the best place for a meeting without an agenda.',
  'The administration does its best with the resources. The students\' patience is also a resource.',
  'There is a suggestion box in the office. We read every one.',
  'Make friends with students outside your department. They will teach you a new way to think.',
  'The monsoon is both our friend and our problem. The drains are good this year.',
  'We introduced new green strips for cycles on the two-lane roads. Please use them.',
  'The students who volunteer for the fests are the unsung heroes. Thank them.',
  'We want the campus to be safe at night. Guards, lights and a few friends help.',
  'Be proud of the place. And honest about what it can improve.',
  'Education is the slow kind of fast. Do not rush.',
  'The campus has a school, a hospital and a market. A small town with a big library.',
  'Please keep to the speed limit of thirty. It is not only a number.',
  'The mess is run by the students and for the students. The Dean eats there too, sometimes.',
  'The Institute has a long list of firsts, and a longer list of things it would like to do.',
  'You can always count on the faculty for a recommendation. If you have earned it.',
  'We wish all our students a happy and healthy time here. If anything goes wrong, come to us.',
  'The best thing about the campus is the people who stay late to help each other.',
  'The campus will be what you make of it. It already is.',
  'I read the student magazine. It is the best way to know what you are thinking.',
  'We are improving the internet. The hostels will thank us. Eventually.',
  'The Pronite is a big event, and we plan the safety with the police and the hospital.',
  'All visitors must carry a pass. All students must carry their ID. It is for everybody\'s safety.',
  'A good institute is one that people want to come back to. I see the alumni in the corridors every year.',
  'Our door is open. Sometimes it is closed, but only because someone is crying or laughing too loudly inside.',
  'We are lucky to be on a hill, by a river, in a forest. Do not forget it while you study.',
  'The future of the campus is in the hands of the people who walk on it every day.',
];

export const director = [
  'Welcome! We are proud of every student here.',
  'Aim high, but look after each other too.',
  'This institute was built on a hill by the Brahmaputra. It has grown, but the hill is still the best part.',
  'A campus is more than buildings. It is the conversations you have on the way to class.',
  'I walk through the campus in the morning. It is my favourite meeting, with no agenda.',
  'Research and teaching are the two feet of the institute. We need both to walk.',
  'The Technology Park is a step towards connecting the campus with the world of start-ups.',
  'We have many labs, many clubs and one lake. I think the lake gets the most visitors.',
  'The students are the reason I get up in the morning. The coffee is the second reason.',
  'The Convocation is the happiest day of the year. I shake thousands of hands and I enjoy every one.',
  'Every student has a story. I wish I could hear them all.',
  'Our institute has a unique location: hills, a river, a forest. We are lucky and we should be responsible.',
  'Our campus is green. Planting a tree takes a minute, and the shade lasts a generation.',
  'Do not hesitate to knock. The doors of the Administrative Building are open.',
  'I was a student once. I remember the long queues, the late nights and the best friends.',
  'Alcheringa and Techniche show the best of the students\' energy. I attend, with earplugs.',
  'Our faculty are the backbone of the institute. Please respect their time.',
  'Innovation does not need a large budget. It needs a curious mind and some free time.',
  'The staff who keep the campus running are the quiet heroes. Please remember to thank them.',
  'The cycle lanes on the two-lane roads are for you. Use them.',
  'We try to keep the campus safe, clean and welcoming. It is a joint effort.',
  'The institute is a family of thousands. Like every family, it has arguments and celebrations.',
  'Please take care of the environment. A single plastic bottle can last longer than all of us.',
  'The View Point trail through the forest is a lovely walk. It reminds us of how much green we have.',
  'The first years always look nervous. I tell them: me too, a little. Then they smile.',
  'The most important skill is the ability to learn, and unlearn, and learn again.',
  'We are building a stronger research culture. Students are part of that, from the first year.',
  'The institute is nothing without its alumni. They are our ambassadors.',
  'The new bus terminus is a small thing, but it makes the commute easier. Small things matter.',
  'We receive visitors from around the world. They always remark on how green the campus is.',
  'Be kind, be curious, and be on time for the lectures.',
  'Our growth is not only in the number of buildings, but in the quality of the questions asked.',
  'The best ideas come after a walk. The campus is a good place to walk.',
  'We have a long way to go, and we have started well.',
  'Make good use of the library. It has everything, including silence.',
  'I wish every student could see the sunrise from the hill. The view puts exams in perspective.',
  'Thank you for your time. Please say hello to your parents for me.',
  'The campus brings together students from every state. It is a small India on a hill.',
  'We try to learn from every festival. What worked, what did not, how to improve next year.',
  'Success is not only a job. It is the kind of person you become on the way.',
  'Teachers are the most patient people I know. Students are the most creative.',
  'I read the student feedback. Some of it is harsh, all of it is useful.',
  'The Pronite stage is ready, and the weather decides the rest.',
  'This campus has been here a few decades. I hope it will be here for centuries.',
  'Take care of your health. The hospital can fix a fever but not the sleep you skip.',
  'We believe in a campus where all are welcome and all are respected.',
  'The institute is also a part of the neighbourhood. We try to help the local schools and villages.',
  'A leader listens first. I try to practise that every day, and sometimes manage.',
  'The security guards are the first people you see when you arrive. Their courtesy matters a lot.',
  'We are lucky to have the Brahmaputra nearby. A river has a lot to teach about patience.',
  'The students\' clubs are the soul of the campus. Support them, join them, lead them.',
  'I enjoy the cultural programmes. Bihu on the stage is a joy.',
  'May your years here be hard enough to teach you and easy enough to enjoy.',
  'Good research takes time. Do not be discouraged if it is slow.',
  'If you see a visitor who looks lost, offer them help. The reputation of the institute is built on such small things.',
  'The campus is for walking, for cycling, for thinking. Cars are guests.',
  'Our start-up cell has ideas that surprise me. I ask them to keep surprising me.',
  'Do read the newsletter. It is where we try to say what is going on.',
  'We are privileged to teach the brightest students. Our responsibility is to show them the world beyond marks.',
  'Education is the greatest equaliser, if it is given with care.',
  'We have solar panels on the cycle sheds and on the hostel roofs. The sun here is generous.',
  'When it rains, I stand for a moment at the window. The campus is at its best in the rain.',
  'The ducks near the lake are a good sign: it means the water is healthy.',
  'You have chosen a hard path. I hope the people around you make it lighter.',
  'The institute is always changing. The values stay the same.',
  'To the students from the North East: you are the heart of this region and of this campus.',
  'The best compliment is when an alumnus says: that place made me who I am.',
  'We are all learning here, even the Director.',
  'Do enjoy the festivals, and do wake up for the Monday class.',
  'I know the mess food is a topic. We are listening, and the committee is working on it.',
  'The Rhino Circle is the first thing visitors see. A good start to a long road.',
  'Treat the campus like your home. It is, for now.',
  'Thank you for being here. Without students, a campus is just a quiet park.',
  'The best use of free time is to try something new: a sport, an instrument, a language.',
  'One day you will come back with your own children. Show them the lake.',
  'We take pride in the research of our faculty and the kindness of our staff.',
  'Be proud of where you come from and curious about where others are from.',
  'The guard post at the KV Gate is 3D printed in cement. I like that we try new things, even at a gate.',
  'The institute\'s motto is about knowledge and light. The lights on the lake at night are a good reminder.',
];
